/*
 * Copyright (C) 2015-2024 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.way;

/**
 * Provides the names of the standard HTML elements.
 */
// Generated by objectos.selfgen.HtmlSpec. Do not edit!
interface HtmlElementNameGenerated {

  /**
   * The {@code a} element.
   */
  public static final Html.ElementName A = HtmlElementName.createNormal("a");

  /**
   * The {@code abbr} element.
   */
  public static final Html.ElementName ABBR = HtmlElementName.createNormal("abbr");

  /**
   * The {@code article} element.
   */
  public static final Html.ElementName ARTICLE = HtmlElementName.createNormal("article");

  /**
   * The {@code b} element.
   */
  public static final Html.ElementName B = HtmlElementName.createNormal("b");

  /**
   * The {@code blockquote} element.
   */
  public static final Html.ElementName BLOCKQUOTE = HtmlElementName.createNormal("blockquote");

  /**
   * The {@code body} element.
   */
  public static final Html.ElementName BODY = HtmlElementName.createNormal("body");

  /**
   * The {@code br} element.
   */
  public static final Html.ElementName BR = HtmlElementName.createVoid("br");

  /**
   * The {@code button} element.
   */
  public static final Html.ElementName BUTTON = HtmlElementName.createNormal("button");

  /**
   * The {@code clipPath} element.
   */
  public static final Html.ElementName CLIPPATH = HtmlElementName.createNormal("clipPath");

  /**
   * The {@code code} element.
   */
  public static final Html.ElementName CODE = HtmlElementName.createNormal("code");

  /**
   * The {@code dd} element.
   */
  public static final Html.ElementName DD = HtmlElementName.createNormal("dd");

  /**
   * The {@code defs} element.
   */
  public static final Html.ElementName DEFS = HtmlElementName.createNormal("defs");

  /**
   * The {@code details} element.
   */
  public static final Html.ElementName DETAILS = HtmlElementName.createNormal("details");

  /**
   * The {@code div} element.
   */
  public static final Html.ElementName DIV = HtmlElementName.createNormal("div");

  /**
   * The {@code dl} element.
   */
  public static final Html.ElementName DL = HtmlElementName.createNormal("dl");

  /**
   * The {@code dt} element.
   */
  public static final Html.ElementName DT = HtmlElementName.createNormal("dt");

  /**
   * The {@code em} element.
   */
  public static final Html.ElementName EM = HtmlElementName.createNormal("em");

  /**
   * The {@code fieldset} element.
   */
  public static final Html.ElementName FIELDSET = HtmlElementName.createNormal("fieldset");

  /**
   * The {@code figure} element.
   */
  public static final Html.ElementName FIGURE = HtmlElementName.createNormal("figure");

  /**
   * The {@code footer} element.
   */
  public static final Html.ElementName FOOTER = HtmlElementName.createNormal("footer");

  /**
   * The {@code form} element.
   */
  public static final Html.ElementName FORM = HtmlElementName.createNormal("form");

  /**
   * The {@code g} element.
   */
  public static final Html.ElementName G = HtmlElementName.createNormal("g");

  /**
   * The {@code h1} element.
   */
  public static final Html.ElementName H1 = HtmlElementName.createNormal("h1");

  /**
   * The {@code h2} element.
   */
  public static final Html.ElementName H2 = HtmlElementName.createNormal("h2");

  /**
   * The {@code h3} element.
   */
  public static final Html.ElementName H3 = HtmlElementName.createNormal("h3");

  /**
   * The {@code h4} element.
   */
  public static final Html.ElementName H4 = HtmlElementName.createNormal("h4");

  /**
   * The {@code h5} element.
   */
  public static final Html.ElementName H5 = HtmlElementName.createNormal("h5");

  /**
   * The {@code h6} element.
   */
  public static final Html.ElementName H6 = HtmlElementName.createNormal("h6");

  /**
   * The {@code head} element.
   */
  public static final Html.ElementName HEAD = HtmlElementName.createNormal("head");

  /**
   * The {@code header} element.
   */
  public static final Html.ElementName HEADER = HtmlElementName.createNormal("header");

  /**
   * The {@code hgroup} element.
   */
  public static final Html.ElementName HGROUP = HtmlElementName.createNormal("hgroup");

  /**
   * The {@code hr} element.
   */
  public static final Html.ElementName HR = HtmlElementName.createVoid("hr");

  /**
   * The {@code html} element.
   */
  public static final Html.ElementName HTML = HtmlElementName.createNormal("html");

  /**
   * The {@code img} element.
   */
  public static final Html.ElementName IMG = HtmlElementName.createVoid("img");

  /**
   * The {@code input} element.
   */
  public static final Html.ElementName INPUT = HtmlElementName.createVoid("input");

  /**
   * The {@code kbd} element.
   */
  public static final Html.ElementName KBD = HtmlElementName.createNormal("kbd");

  /**
   * The {@code label} element.
   */
  public static final Html.ElementName LABEL = HtmlElementName.createNormal("label");

  /**
   * The {@code legend} element.
   */
  public static final Html.ElementName LEGEND = HtmlElementName.createNormal("legend");

  /**
   * The {@code li} element.
   */
  public static final Html.ElementName LI = HtmlElementName.createNormal("li");

  /**
   * The {@code link} element.
   */
  public static final Html.ElementName LINK = HtmlElementName.createVoid("link");

  /**
   * The {@code main} element.
   */
  public static final Html.ElementName MAIN = HtmlElementName.createNormal("main");

  /**
   * The {@code menu} element.
   */
  public static final Html.ElementName MENU = HtmlElementName.createNormal("menu");

  /**
   * The {@code meta} element.
   */
  public static final Html.ElementName META = HtmlElementName.createVoid("meta");

  /**
   * The {@code nav} element.
   */
  public static final Html.ElementName NAV = HtmlElementName.createNormal("nav");

  /**
   * The {@code ol} element.
   */
  public static final Html.ElementName OL = HtmlElementName.createNormal("ol");

  /**
   * The {@code optgroup} element.
   */
  public static final Html.ElementName OPTGROUP = HtmlElementName.createNormal("optgroup");

  /**
   * The {@code option} element.
   */
  public static final Html.ElementName OPTION = HtmlElementName.createNormal("option");

  /**
   * The {@code p} element.
   */
  public static final Html.ElementName P = HtmlElementName.createNormal("p");

  /**
   * The {@code path} element.
   */
  public static final Html.ElementName PATH = HtmlElementName.createNormal("path");

  /**
   * The {@code pre} element.
   */
  public static final Html.ElementName PRE = HtmlElementName.createNormal("pre");

  /**
   * The {@code progress} element.
   */
  public static final Html.ElementName PROGRESS = HtmlElementName.createNormal("progress");

  /**
   * The {@code samp} element.
   */
  public static final Html.ElementName SAMP = HtmlElementName.createNormal("samp");

  /**
   * The {@code script} element.
   */
  public static final Html.ElementName SCRIPT = HtmlElementName.createNormal("script");

  /**
   * The {@code section} element.
   */
  public static final Html.ElementName SECTION = HtmlElementName.createNormal("section");

  /**
   * The {@code select} element.
   */
  public static final Html.ElementName SELECT = HtmlElementName.createNormal("select");

  /**
   * The {@code small} element.
   */
  public static final Html.ElementName SMALL = HtmlElementName.createNormal("small");

  /**
   * The {@code span} element.
   */
  public static final Html.ElementName SPAN = HtmlElementName.createNormal("span");

  /**
   * The {@code strong} element.
   */
  public static final Html.ElementName STRONG = HtmlElementName.createNormal("strong");

  /**
   * The {@code style} element.
   */
  public static final Html.ElementName STYLE = HtmlElementName.createNormal("style");

  /**
   * The {@code sub} element.
   */
  public static final Html.ElementName SUB = HtmlElementName.createNormal("sub");

  /**
   * The {@code summary} element.
   */
  public static final Html.ElementName SUMMARY = HtmlElementName.createNormal("summary");

  /**
   * The {@code sup} element.
   */
  public static final Html.ElementName SUP = HtmlElementName.createNormal("sup");

  /**
   * The {@code svg} element.
   */
  public static final Html.ElementName SVG = HtmlElementName.createNormal("svg");

  /**
   * The {@code table} element.
   */
  public static final Html.ElementName TABLE = HtmlElementName.createNormal("table");

  /**
   * The {@code tbody} element.
   */
  public static final Html.ElementName TBODY = HtmlElementName.createNormal("tbody");

  /**
   * The {@code td} element.
   */
  public static final Html.ElementName TD = HtmlElementName.createNormal("td");

  /**
   * The {@code template} element.
   */
  public static final Html.ElementName TEMPLATE = HtmlElementName.createNormal("template");

  /**
   * The {@code textarea} element.
   */
  public static final Html.ElementName TEXTAREA = HtmlElementName.createNormal("textarea");

  /**
   * The {@code th} element.
   */
  public static final Html.ElementName TH = HtmlElementName.createNormal("th");

  /**
   * The {@code thead} element.
   */
  public static final Html.ElementName THEAD = HtmlElementName.createNormal("thead");

  /**
   * The {@code title} element.
   */
  public static final Html.ElementName TITLE = HtmlElementName.createNormal("title");

  /**
   * The {@code tr} element.
   */
  public static final Html.ElementName TR = HtmlElementName.createNormal("tr");

  /**
   * The {@code ul} element.
   */
  public static final Html.ElementName UL = HtmlElementName.createNormal("ul");

}
