/*
 * Copyright (C) 2015-2025 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.way;

/**
 * Provides the names of the standard HTML elements.
 */
// Generated by objectos.selfgen.HtmlSpec. Do not edit!
interface HtmlElementNameGenerated {

  /**
   * The {@code a} element.
   */
  public static final Html.ElementName A = HtmlElementName.A;

  /**
   * The {@code abbr} element.
   */
  public static final Html.ElementName ABBR = HtmlElementName.ABBR;

  /**
   * The {@code article} element.
   */
  public static final Html.ElementName ARTICLE = HtmlElementName.ARTICLE;

  /**
   * The {@code b} element.
   */
  public static final Html.ElementName B = HtmlElementName.B;

  /**
   * The {@code blockquote} element.
   */
  public static final Html.ElementName BLOCKQUOTE = HtmlElementName.BLOCKQUOTE;

  /**
   * The {@code body} element.
   */
  public static final Html.ElementName BODY = HtmlElementName.BODY;

  /**
   * The {@code br} element.
   */
  public static final Html.ElementName BR = HtmlElementName.BR;

  /**
   * The {@code button} element.
   */
  public static final Html.ElementName BUTTON = HtmlElementName.BUTTON;

  /**
   * The {@code clipPath} element.
   */
  public static final Html.ElementName CLIPPATH = HtmlElementName.CLIPPATH;

  /**
   * The {@code code} element.
   */
  public static final Html.ElementName CODE = HtmlElementName.CODE;

  /**
   * The {@code dd} element.
   */
  public static final Html.ElementName DD = HtmlElementName.DD;

  /**
   * The {@code defs} element.
   */
  public static final Html.ElementName DEFS = HtmlElementName.DEFS;

  /**
   * The {@code details} element.
   */
  public static final Html.ElementName DETAILS = HtmlElementName.DETAILS;

  /**
   * The {@code div} element.
   */
  public static final Html.ElementName DIV = HtmlElementName.DIV;

  /**
   * The {@code dl} element.
   */
  public static final Html.ElementName DL = HtmlElementName.DL;

  /**
   * The {@code dt} element.
   */
  public static final Html.ElementName DT = HtmlElementName.DT;

  /**
   * The {@code em} element.
   */
  public static final Html.ElementName EM = HtmlElementName.EM;

  /**
   * The {@code fieldset} element.
   */
  public static final Html.ElementName FIELDSET = HtmlElementName.FIELDSET;

  /**
   * The {@code figure} element.
   */
  public static final Html.ElementName FIGURE = HtmlElementName.FIGURE;

  /**
   * The {@code footer} element.
   */
  public static final Html.ElementName FOOTER = HtmlElementName.FOOTER;

  /**
   * The {@code form} element.
   */
  public static final Html.ElementName FORM = HtmlElementName.FORM;

  /**
   * The {@code g} element.
   */
  public static final Html.ElementName G = HtmlElementName.G;

  /**
   * The {@code h1} element.
   */
  public static final Html.ElementName H1 = HtmlElementName.H1;

  /**
   * The {@code h2} element.
   */
  public static final Html.ElementName H2 = HtmlElementName.H2;

  /**
   * The {@code h3} element.
   */
  public static final Html.ElementName H3 = HtmlElementName.H3;

  /**
   * The {@code h4} element.
   */
  public static final Html.ElementName H4 = HtmlElementName.H4;

  /**
   * The {@code h5} element.
   */
  public static final Html.ElementName H5 = HtmlElementName.H5;

  /**
   * The {@code h6} element.
   */
  public static final Html.ElementName H6 = HtmlElementName.H6;

  /**
   * The {@code head} element.
   */
  public static final Html.ElementName HEAD = HtmlElementName.HEAD;

  /**
   * The {@code header} element.
   */
  public static final Html.ElementName HEADER = HtmlElementName.HEADER;

  /**
   * The {@code hgroup} element.
   */
  public static final Html.ElementName HGROUP = HtmlElementName.HGROUP;

  /**
   * The {@code hr} element.
   */
  public static final Html.ElementName HR = HtmlElementName.HR;

  /**
   * The {@code html} element.
   */
  public static final Html.ElementName HTML = HtmlElementName.HTML;

  /**
   * The {@code img} element.
   */
  public static final Html.ElementName IMG = HtmlElementName.IMG;

  /**
   * The {@code input} element.
   */
  public static final Html.ElementName INPUT = HtmlElementName.INPUT;

  /**
   * The {@code kbd} element.
   */
  public static final Html.ElementName KBD = HtmlElementName.KBD;

  /**
   * The {@code label} element.
   */
  public static final Html.ElementName LABEL = HtmlElementName.LABEL;

  /**
   * The {@code legend} element.
   */
  public static final Html.ElementName LEGEND = HtmlElementName.LEGEND;

  /**
   * The {@code li} element.
   */
  public static final Html.ElementName LI = HtmlElementName.LI;

  /**
   * The {@code link} element.
   */
  public static final Html.ElementName LINK = HtmlElementName.LINK;

  /**
   * The {@code main} element.
   */
  public static final Html.ElementName MAIN = HtmlElementName.MAIN;

  /**
   * The {@code menu} element.
   */
  public static final Html.ElementName MENU = HtmlElementName.MENU;

  /**
   * The {@code meta} element.
   */
  public static final Html.ElementName META = HtmlElementName.META;

  /**
   * The {@code nav} element.
   */
  public static final Html.ElementName NAV = HtmlElementName.NAV;

  /**
   * The {@code ol} element.
   */
  public static final Html.ElementName OL = HtmlElementName.OL;

  /**
   * The {@code optgroup} element.
   */
  public static final Html.ElementName OPTGROUP = HtmlElementName.OPTGROUP;

  /**
   * The {@code option} element.
   */
  public static final Html.ElementName OPTION = HtmlElementName.OPTION;

  /**
   * The {@code p} element.
   */
  public static final Html.ElementName P = HtmlElementName.P;

  /**
   * The {@code path} element.
   */
  public static final Html.ElementName PATH = HtmlElementName.PATH;

  /**
   * The {@code pre} element.
   */
  public static final Html.ElementName PRE = HtmlElementName.PRE;

  /**
   * The {@code progress} element.
   */
  public static final Html.ElementName PROGRESS = HtmlElementName.PROGRESS;

  /**
   * The {@code samp} element.
   */
  public static final Html.ElementName SAMP = HtmlElementName.SAMP;

  /**
   * The {@code script} element.
   */
  public static final Html.ElementName SCRIPT = HtmlElementName.SCRIPT;

  /**
   * The {@code section} element.
   */
  public static final Html.ElementName SECTION = HtmlElementName.SECTION;

  /**
   * The {@code select} element.
   */
  public static final Html.ElementName SELECT = HtmlElementName.SELECT;

  /**
   * The {@code small} element.
   */
  public static final Html.ElementName SMALL = HtmlElementName.SMALL;

  /**
   * The {@code span} element.
   */
  public static final Html.ElementName SPAN = HtmlElementName.SPAN;

  /**
   * The {@code strong} element.
   */
  public static final Html.ElementName STRONG = HtmlElementName.STRONG;

  /**
   * The {@code style} element.
   */
  public static final Html.ElementName STYLE = HtmlElementName.STYLE;

  /**
   * The {@code sub} element.
   */
  public static final Html.ElementName SUB = HtmlElementName.SUB;

  /**
   * The {@code summary} element.
   */
  public static final Html.ElementName SUMMARY = HtmlElementName.SUMMARY;

  /**
   * The {@code sup} element.
   */
  public static final Html.ElementName SUP = HtmlElementName.SUP;

  /**
   * The {@code svg} element.
   */
  public static final Html.ElementName SVG = HtmlElementName.SVG;

  /**
   * The {@code table} element.
   */
  public static final Html.ElementName TABLE = HtmlElementName.TABLE;

  /**
   * The {@code tbody} element.
   */
  public static final Html.ElementName TBODY = HtmlElementName.TBODY;

  /**
   * The {@code td} element.
   */
  public static final Html.ElementName TD = HtmlElementName.TD;

  /**
   * The {@code template} element.
   */
  public static final Html.ElementName TEMPLATE = HtmlElementName.TEMPLATE;

  /**
   * The {@code textarea} element.
   */
  public static final Html.ElementName TEXTAREA = HtmlElementName.TEXTAREA;

  /**
   * The {@code th} element.
   */
  public static final Html.ElementName TH = HtmlElementName.TH;

  /**
   * The {@code thead} element.
   */
  public static final Html.ElementName THEAD = HtmlElementName.THEAD;

  /**
   * The {@code title} element.
   */
  public static final Html.ElementName TITLE = HtmlElementName.TITLE;

  /**
   * The {@code tr} element.
   */
  public static final Html.ElementName TR = HtmlElementName.TR;

  /**
   * The {@code ul} element.
   */
  public static final Html.ElementName UL = HtmlElementName.UL;

}
