/*
 * Copyright (C) 2023-2025 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.way;

import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;

/*
 * Do not edit: this class was generated by ScriptLibraryGen.java.
 */
enum ScriptLibrary implements Script.Library {

  INSTANCE;

  @Override
  public final String contentType() {
    return "text/javascript; charset=utf-8";
  }

  @Override
  public final Charset charset() {
    return StandardCharsets.UTF_8;
  }

  @Override
  public final void writeTo(Appendable out) throws IOException {
    out.append(toString());
  }

  @Override
  public final String toString() {
    return """
/*
 * Copyright (C) 2023-2025 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
const way = (function() {

  "use strict";

  const way = {

    config: {

      errorHandler: function(error) {
        throw error;
      },

      history: true

    }

  };

  // ##################################################################
  // # BEGIN: DOM Event Handlers
  // ##################################################################

  function clickListener(event) {
    let el = event.target;

    while (el instanceof Node) {
      const result = executeEvent(el, "onClick");

      if (result) {
        event.preventDefault();

        break;
      }

      // there was no data-on-click action...
      // but we explicitly stop at these elements

      if (el instanceof HTMLAnchorElement) {
        break;
      }

      if (el instanceof HTMLButtonElement) {
        break;
      }

      // continue with this element's parent

      el = el.parentNode;
    }
  }

  function executeEvent(el, name) {
    const dataset = el.dataset;

    if (!dataset) {
      return false;
    }

    const data = dataset[name];

    if (!data) {
      return false;
    }

    const way = JSON.parse(data);

    executeWay(el, way);

    return true;
  }

  // ##################################################################
  // # END: DOM Event Handlers
  // ##################################################################

  // ##################################################################
  // # BEGIN: Objectos Way Actions
  // ##################################################################

  const operations = {
    "CR": contextRead,
    "CW": contextWrite,
    "EI": elementById,
    "ET": elementTarget,
    "FE": forEach,
    "IV": invokeVirtual,
    "PR": propertyRead,
    "PW": propertyWrite
  };

  function nest(ctx, actions) {
    checkArray(actions, "actions");

    return (...args) => {
      const nested = { ...ctx };

      nested.$args = args;

      for (const a of actions) {
        executeAction(nested, a);
      }
    };
  }

  function executeWay(el, actions) {
    checkArray(actions, "actions");

    const ctx = {
      $el: el,
      $recv: undefined
    };

    for (const a of actions) {
      executeAction(ctx, a);
    }

    return true;
  }

  function executeAction(ctx, action) {
    checkArray(action, "action");

    for (const op of action) {
      ctx.$recv = executeOperation(ctx, op);
    }
  }

  function executeOperation(ctx, op) {
    checkArray(op, "operation");

    const id = checkString(op.shift(), "id");

    const handler = operations[id];

    if (handler) {
      return handler(ctx, op);
    } else {
      throw new Error(`Illegal arg: no handler found for operation=${id}`);
    }
  }

  function arg(ctx, arg) {
    checkArray(arg, "arg");

    const kind = checkString(arg.shift(), "kind");

    switch (kind) {
      case "JS":
        return arg.shift();

      case "WA":
        const action = arg.shift();

        executeAction(ctx, action);

        return ctx.$recv;

      default:
        throw new Error(`Illegal arg: unknown arg kind=${kind}`);
    }
  }

  function contextRead(ctx, args) {
    const name = contextName(args.shift());

    return ctx[name];
  }

  function contextWrite(ctx, args) {
    const name = contextName(args.shift());

    const val = checkDefined(args.shift(), "value");

    ctx[name] = arg(ctx, val);
  }

  function contextName(maybe) {
    const name = checkString(maybe, "name");

    if (name.length === 0) {
      throw new Error("Illegal arg: context variable name must not be empty");
    }

    if (name.startsWith("$")) {
      throw new Error("Illegal arg: context variable name must not begin with the '$' character");
    }

    return name;
  }

  function elementById(_, args) {
    const id = checkString(args.shift(), "id");

    const element = document.getElementById(id);

    if (!element) {
      throw new Error(`Illegal arg: element not found with ID ${id}`);
    }

    return element;
  }

  function elementTarget(ctx, _) {
    return ctx.$el;
  }

  function forEach(ctx, args) {
    const recv = checkRecv(ctx, args.shift());

    const actions = checkDefined(args.shift(), "actions");

    const fn = nest(ctx, actions);

    recv.forEach(fn);
  }

  function invokeVirtual(ctx, args) {
    const recv = checkRecv(ctx, args.shift());

    const methodName = checkString(args.shift(), "methodName");

    const method = recv[methodName];

    if (!method) {
      throw new Error(`Illegal arg: ${typeName} does not declare the ${methodName} method`);
    }

    const encodedArgs = checkArray(args.shift(), "encodedArgs");

    const methodArgs = encodedArgs.map(x => arg(ctx, x));

    return method.call(recv, methodArgs);
  }

  function propertyRead(ctx, args) {
    const recv = checkRecv(ctx, args.shift());

    const propName = checkString(args.shift(), "propName");

    const prop = recv[propName];

    if (!prop) {
      throw new Error(`Illegal arg: ${typeName} does not declare the ${propName} property`);
    }

    return prop;
  }

  function propertyWrite(ctx, args) {
    const recv = checkRecv(ctx, args.shift());

    const propName = checkString(args.shift(), "propName");

    const val = checkDefined(args.shift(), "value");

    recv[propName] = arg(ctx, val);
  }

  // ##################################################################
  // # END: Objectos Way Actions
  // ##################################################################

  // ##################################################################
  // # BEGIN: private private
  // ##################################################################

  function checkArray(maybe, name) {
    if (!Array.isArray(maybe)) {
      throw new Error(`Illegal arg: ${name} must be an Array value but got ${maybe}`);
    }

    return maybe;
  }

  function checkDefined(maybe, name) {
    if (!maybe) {
      throw new Error(`Illegal arg: ${name} must be a defined value`);
    }

    return maybe;
  }

  function checkRecv(ctx, tn) {
    const typeName = checkString(tn, "typeName");

    const recv = ctx.$recv;

    checkType(recv, "recv", typeName);

    return recv;
  }

  function checkType(maybe, name, typeName) {
    const t = typeof maybe;

    if (t !== "object") {
      throw new Error(`Illegal arg: ${name} must be an Object value but got ${t}`);
    }

    let prototype = Object.getPrototypeOf(maybe);

    while (prototype) {
      const constructor = prototype.constructor;

      if (!constructor) {
        throw new Error(`Illegal arg: expected ${name} to have a constructor, but found ${constructor}`);
      }

      const actualName = constructor.name;

      if (actualName === typeName) {
        return maybe;
      }

      prototype = Object.getPrototypeOf(prototype);
    }

    throw new Error(`Illegal arg: ${name} does not have ${typeName} in its prototype chain`);
  }

  function checkString(maybe, name) {
    const t = typeof maybe;

    if (t !== "string") {
      throw new Error(`Illegal arg: ${name} must be a String value but got ${t}`);
    }

    return maybe;
  }

  // ##################################################################
  // # END: private private
  // ##################################################################

  // ##################################################################
  // # BEGIN: Objectos Way Bootstrap
  // ##################################################################

  function listener(actual) {
    return function(event) {
      try {
        actual.call(this, event)
      } catch (error) {
        way.config.errorHandler(error);
      }
    };
  }

  function domLoaded() {
    document.addEventListener("click", listener(clickListener));
  }

  window.addEventListener("DOMContentLoaded", domLoaded);

  // ##################################################################
  // # END: Objectos Way Bootstrap
  // ##################################################################

  return way;

})();
""";
  }

}
