/*
 * Copyright (C) 2023-2025 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;

public final class CssPropsGen {

  private CssPropsGen() {}

  public static void main(String[] args) throws IOException {
    final Path sourceFile;
    sourceFile = Path.of("work", "css-props.txt");

    final Path targetFile;
    targetFile = Path.of("main", "objectos", "way", "CssProps.java");

    try (
        final BufferedWriter w = Files.newBufferedWriter(
            targetFile, StandardCharsets.UTF_8,
            StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING
        );
    ) {

      w.write("""
      /*
       * Copyright (C) 2023-2025 Objectos Software LTDA.
       *
       * Licensed under the Apache License, Version 2.0 (the "License");
       * you may not use this file except in compliance with the License.
       * You may obtain a copy of the License at
       *
       * http://www.apache.org/licenses/LICENSE-2.0
       *
       * Unless required by applicable law or agreed to in writing, software
       * distributed under the License is distributed on an "AS IS" BASIS,
       * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       * See the License for the specific language governing permissions and
       * limitations under the License.
       */
      package objectos.way;
      
      import java.util.Set;

      /*
       * Do not edit: this class was generated by CssPropsGen.java
       */
      final class CssProps {
        private CssProps() {}
        
        static Set<String> get() {
          return Set.of(
      """);

      var lines = Files.readAllLines(sourceFile, StandardCharsets.UTF_8);
      
      int idx = 0;
      
      for (String line : lines) {
        if ("--*".equals(line)) {
          continue;
        }

        if (idx++ != 0) {
          w.write(",\n");
        }
        
        w.write("        \"");
        
        // we expected a css property name to not contain a '"' char
        w.write(line);
        
        w.write("\"");
      }
      
      w.write("""
      
          );
        }
      }
      """);
    }
  }

}