/*
 * Copyright (C) 2023 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.css.util;

import objectos.html.tmpl.Api.ExternalAttribute.StyleClass;
import objectox.css.ClassSelectorSeqId;

/**
 * Utility classes for the {@code display} CSS property.
 */
// Generated by selfgen.css.CssUtilSpec. Do not edit!
public enum Display implements StyleClass {

  NONE,

  BLOCK,

  FLOW_ROOT,

  INLINE_BLOCK,

  INLINE,

  FLEX,

  INLINE_FLEX,

  GRID,

  INLINE_GRID,

  TABLE,

  TABLE_CAPTION,

  TABLE_CELL,

  TABLE_COLUMN,

  TABLE_COLUMN_GROUP,

  TABLE_FOOTER_GROUP,

  TABLE_HEADER_GROUP,

  TABLE_ROW_GROUP,

  TABLE_ROW;

  private final String className = ClassSelectorSeqId.next();

  @Override
  public final String className() {
    return className;
  }

}
