/*
 * Copyright (C) 2023 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.css.util;

import objectos.html.tmpl.Api.ExternalAttribute.StyleClass;
import objectox.css.ClassSelectorSeqId;

/**
 * Utility classes for the {@code font-size} and {@code line-height} CSS properties.
 */
// Generated by selfgen.css.CssUtilSpec. Do not edit!
public enum FontSize implements StyleClass {

  XS("0.75rem", "1rem"),

  SM("0.875rem", "1.25rem"),

  BASE("1rem", "1.5rem"),

  LG("1.125rem", "1.75rem"),

  XL("1.25rem", "1.75rem"),

  XL2("1.5rem", "2rem"),

  XL3("1.875rem", "2.25rem"),

  XL4("2.25rem", "2.5rem"),

  XL5("3rem", "1"),

  XL6("3.75rem", "1"),

  XL7("4.5rem", "1"),

  XL8("6rem", "1"),

  XL9("8rem", "1");

  private final String className = ClassSelectorSeqId.next();

  private final String value1;

  private final String value2;

  private FontSize(String value1, String value2) {
    this.value1 = value1;
    this.value2 = value2;
  }

  /**
   * Returns the CSS class name.
   *
   * @return the CSS class name
   */
  @Override
  public final String className() {
    return className;
  }

  /**
   * Returns the CSS style rule represented by this utility class.
   *
   * @return the CSS style rule
   */
  @Override
  public final String toString() {
    return "." + className + " { font-size: " + value1 + "; line-height: " + value2 + " }";
  }

}
