/*
 * Copyright (C) 2023-2026 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.html;

import objectos.dev.Testable;
import objectos.http.Content;
import objectos.http.ContentProvider;
import objectos.http.MediaType;

/// An object that renders HTML on its own or as part of a larger
/// HTML document.
@FunctionalInterface
public interface Component extends ContentProvider, Testable {

  /// Returns the markup instance to be used by this component.
  ///
  /// @return the markup instance to be used by this component
  default Markup newHtmlMarkup() {
    return new Markup.OfHtml();
  }

  /// Renders the HTML of this component.
  ///
  /// @param m the markup object to use
  void renderHtml(Markup m);

  /// Returns a new `Content` object with the `text/html; charset=utf-8` type
  /// and capable of writing the generated HTML.
  ///
  /// @return a newly created `Content` object
  @Override
  default Content toContent() {
    final Markup html;
    html = newHtmlMarkup();

    renderHtml(html);
    
    return Content.of(MediaType.TEXT_HTML, html);
  }

  /// Returns the HTML generated by this component.
  ///
  /// @return the HTML generated by this component
  default String toHtml() {
    final Markup html;
    html = newHtmlMarkup();

    renderHtml(html);

    return html.toHtml();
  }

  /// Returns the formatted string representation of the testable nodes of
  /// this component.
  ///
  /// @return the formatted string representation of the testable nodes of
  ///         this component
  @Override
  default String toTestableText() {
    final Markup html;
    html = new Markup.OfHtml();

    renderHtml(html);

    return html.toTestableText();
  }

}