/*
 * Copyright (C) 2023-2026 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.html;

import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import objectos.dev.Testable;
import objectos.html.rec.ElementMarkup;
import objectos.html.rec.Fragment0;
import objectos.html.rec.Fragment1;
import objectos.html.rec.Fragment2;
import objectos.html.rec.Fragment3;
import objectos.html.rec.Fragment4;
import objectos.html.rec.Instruction;
import objectos.lang.BinaryObject;
import objectos.script.JsAction;
import objectox.html.MarkupPojo;

/// Declares the structure of an HTML document using pure Java.
public sealed interface Markup extends BinaryObject, Testable permits MarkupPojo {

  /// Markup implementation for generating HTML.
  non-sealed class OfHtml extends MarkupPojo  {

    /// Sole constructor.
    public OfHtml() {}

  }

  /// Renders the specified attribute at the root of a document or fragment.
  ///
  /// @param object the attribute
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute attr(AttributeObject object);

  /// Writes the HTML generated by this component to the specified output
  /// stream using the `UTF-8` charset.
  ///
  /// @param out the destination output stream
  ///
  /// @throws IOException if an I/O error occurs
  @Override
  default void binaryTo(OutputStream out) throws IOException {
    final OutputStreamWriter writer;
    writer = new OutputStreamWriter(out, StandardCharsets.UTF_8);

    writeTo(writer);

    writer.flush();
  }

  /// Generates and returns the HTML represented by this markup instance.
  ///
  /// @return the HTML represented by this markup instance.
  String toHtml();

  /// Writes out the HTML generated by this markup instance. This method may
  /// be invoked at most once per markup instance.
  ///
  /// @param out where to write out the HTML
  ///
  /// @throws IOException if an I/O error occurs
  void writeTo(Appendable out) throws IOException;

  // START generated code

  /// The `async` boolean attribute.
  AttributeObject async = AttributeObject.of(AttributeName.ASYNC);

  /// The `autofocus` boolean attribute.
  AttributeObject autofocus = AttributeObject.of(AttributeName.AUTOFOCUS);

  /// The `checked` boolean attribute.
  AttributeObject checked = AttributeObject.of(AttributeName.CHECKED);

  /// The `defer` boolean attribute.
  AttributeObject defer = AttributeObject.of(AttributeName.DEFER);

  /// The `disabled` boolean attribute.
  AttributeObject disabled = AttributeObject.of(AttributeName.DISABLED);

  /// The `hidden` boolean attribute.
  AttributeObject hidden = AttributeObject.of(AttributeName.HIDDEN);

  /// The `multiple` boolean attribute.
  AttributeObject multiple = AttributeObject.of(AttributeName.MULTIPLE);

  /// The `nomodule` boolean attribute.
  AttributeObject nomodule = AttributeObject.of(AttributeName.NOMODULE);

  /// The `open` boolean attribute.
  AttributeObject open = AttributeObject.of(AttributeName.OPEN);

  /// The `readonly` boolean attribute.
  AttributeObject readonly = AttributeObject.of(AttributeName.READONLY);

  /// The `required` boolean attribute.
  AttributeObject required = AttributeObject.of(AttributeName.REQUIRED);

  /// The `reversed` boolean attribute.
  AttributeObject reversed = AttributeObject.of(AttributeName.REVERSED);

  /// The `selected` boolean attribute.
  AttributeObject selected = AttributeObject.of(AttributeName.SELECTED);

  //
  // WAY
  //

  /// Renders the `class` attribute by processing the specified value.
  ///
  /// This method is designed to work with Java text blocks. It first removes
  /// any leading and trailing whitespace. Additionally, any sequence of
  /// consecutive whitespace characters is replaced by a single space
  /// character.
  ///
  /// For example, the following invocation:
  ///
  /// ```java css(""" display:inline-flex justify-content:center
  ///
  /// background-color:blue-500 """); ```
  ///
  /// Produces the same result as invoking `className("display:inline-flex
  /// justify-content:center background-color:blue-500")`.
  ///
  /// @param value the text block containing class names, possibly spread
  /// across multiple lines
  ///
  /// @return an instruction representing this attribute.
  Instruction.OfAttribute css(String value);

  /// Renders the specified components in order as part of this document.
  ///
  /// @param components the components to be rendered as part of this document
  ///
  /// @return an instruction representing the rendered components.
  Instruction.OfFragment c(Component... components);

  /// Renders the specified components in order as part of this document.
  ///
  /// @param components the components to be rendered as part of this document
  ///
  /// @return an instruction representing the rendered components.
  Instruction.OfFragment c(Iterable<? extends Component> components);

  /// Renders the specified fragment as part of this document.
  ///
  /// The following Objectos HTML component:
  ///
  /// {@snippet file = "objectos/way/HtmlMarkupJavadoc.java" region = "f0"}
  ///
  /// Generates the following HTML:
  ///
  /// ```html
  /// <ul>
  /// <li>Mon</li>
  /// <li>Wed</li>
  /// <li>Fri</li>
  /// </ul>
  /// ```
  ///
  /// @param fragment the fragment to include
  ///
  /// @return an instruction representing the fragment
  Instruction.OfFragment f(Fragment0 fragment);

  /// Renders the specified fragment as part of this document.
  ///
  /// The following Objectos HTML component:
  ///
  /// {@snippet file = "objectos/way/HtmlMarkupJavadoc.java" region = "f1"}
  ///
  /// Generates the following HTML:
  ///
  /// ```html
  /// <ul>
  /// <li>Mon</li>
  /// <li>Wed</li>
  /// <li>Fri</li>
  /// </ul>
  /// ```
  ///
  /// @param <T1> the type of the first argument
  /// @param fragment the fragment to include
  /// @param arg1 the first argument
  ///
  /// @return an instruction representing the fragment
  <T1> Instruction.OfFragment f(Fragment1<T1> fragment, T1 arg1);

  /// Renders the specified fragment as part of this document.
  ///
  /// The following Objectos HTML component:
  ///
  /// {@snippet file = "objectos/way/HtmlMarkupJavadoc.java" region = "f2"}
  ///
  /// Generates the following HTML:
  ///
  /// ```html <div><button>OK</button><button>Cancel</button></div> ```
  ///
  /// @param <T1> the type of the first argument
  /// @param <T2> the type of the second argument
  /// @param fragment the fragment to include
  /// @param arg1 the first argument
  /// @param arg2 the second argument
  ///
  /// @return an instruction representing the fragment
  <T1, T2> Instruction.OfFragment f(Fragment2<T1, T2> fragment, T1 arg1, T2 arg2);

  /// Renders the specified fragment as part of this document.
  ///
  /// The following Objectos HTML component:
  ///
  /// {@snippet file = "objectos/way/HtmlMarkupJavadoc.java" region = "f3"}
  ///
  /// Generates the following HTML:
  ///
  /// ```html
  /// <div>
  /// <p>
  /// City<span>Tokyo</span>
  /// </p>
  /// <p>
  /// Country<span>Japan</span>
  /// </p>
  /// </div>
  /// ```
  ///
  /// @param <T1> the type of the first argument
  /// @param <T2> the type of the second argument
  /// @param <T3> the type of the third argument
  /// @param fragment the fragment to include
  /// @param arg1 the first argument
  /// @param arg2 the second argument
  /// @param arg3 the third argument
  ///
  /// @return an instruction representing the fragment
  <T1, T2, T3> Instruction.OfFragment f(Fragment3<T1, T2, T3> fragment, T1 arg1, T2 arg2, T3 arg3);

  /// Renders the specified fragment as part of this document.
  ///
  /// @param <T1> the type of the first argument
  /// @param <T2> the type of the second argument
  /// @param <T3> the type of the third argument
  /// @param <T4> the type of the fourth argument
  /// @param fragment the fragment to include
  /// @param arg1 the first argument
  /// @param arg2 the second argument
  /// @param arg3 the third argument
  /// @param arg4 the fourth argument
  ///
  /// @return an instruction representing the fragment
  <T1, T2, T3, T4> Instruction.OfFragment f(Fragment4<T1, T2, T3, T4> fragment, T1 arg1, T2 arg2, T3 arg3, T4 arg4);

  /// Flattens the specified instructions so that each of the specified
  /// instructions is individually added, in order, to a receiving element.
  ///
  /// @param contents the instructions to be flattened
  ///
  /// @return an instruction representing this flatten operation
  ElementMarkup flatten(Instruction... contents);

  /// Flattens the specified instructions so that each of the specified
  /// instructions is individually added, in order, to a receiving element.
  ///
  /// @param contents the instructions to be flattened
  ///
  /// @return an instruction representing this flatten operation
  ElementMarkup flatten(Iterable<? extends Instruction> contents);

  /// The no-op instruction.
  ///
  /// @return the no-op instruction.
  Instruction.NoOp noop();

  //
  // TESTABLE
  //

  /// Formats the specified value as a testable table cell with the specified
  /// fixed width (optional operation).
  ///
  /// @param value the cell value
  /// @param width the fixed width of the cell
  ///
  /// @return always the cell value
  String testableCell(String value, int width);

  /// Formats the specified name and value as a testable field (optional
  /// operation).
  ///
  /// @param name the field name
  /// @param value the field value
  ///
  /// @return always the field value
  String testableField(String name, String value);

  /// Formats the specified name as a testable field name (optional
  /// operation).
  ///
  /// @param name the field name
  ///
  /// @return the specified field name
  String testableFieldName(String name);

  /// Formats the specified value as a testable field value (optional
  /// operation).
  ///
  /// @param value the field value
  ///
  /// @return the specified field value
  String testableFieldValue(String value);

  /// Formats the specified value as a testable heading level 1 (optional
  /// operation).
  ///
  /// @param value the heading value
  ///
  /// @return the specified value
  String testableH1(String value);

  /// Formats the specified value as a testable heading level 2 (optional
  /// operation).
  ///
  /// @param value the heading value
  ///
  /// @return the specified value
  String testableH2(String value);

  /// Formats the specified value as a testable heading level 3 (optional
  /// operation).
  ///
  /// @param value the heading value
  ///
  /// @return the specified value
  String testableH3(String value);

  /// Formats the specified value as a testable heading level 4 (optional
  /// operation).
  ///
  /// @param value the heading value
  ///
  /// @return the specified value
  String testableH4(String value);

  /// Formats the specified value as a testable heading level 5 (optional
  /// operation).
  ///
  /// @param value the heading value
  ///
  /// @return the specified value
  String testableH5(String value);

  /// Formats the specified value as a testable heading level 6 (optional
  /// operation).
  ///
  /// @param value the heading value
  ///
  /// @return the specified value
  String testableH6(String value);

  /// Formats a line separator at the testable output exclusively (optional
  /// operation).
  ///
  /// @return a no-op instruction
  Instruction.NoOp testableNewLine();

  //
  // ELEMENTS
  //

  /// Renders an HTML element with the specified name and contents.
  ///
  /// @param name the element name
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element
  ElementMarkup elem(ElementName name, Instruction... contents);

  /// Renders an HTML element with the specified name and text.
  ///
  /// @param name the element name
  /// @param text the text value of this element
  ///
  /// @return an instruction representing the element
  ElementMarkup elem(ElementName name, String text);

  /// Renders the `<!DOCTYPE html>` doctype.
  void doctype();

  /// Renders the `a` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup a(Instruction... contents);

  /// Renders the `a` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup a(String text);

  /// Renders the `abbr` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup abbr(Instruction... contents);

  /// Renders the `abbr` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup abbr(String text);

  /// Renders the `article` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup article(Instruction... contents);

  /// Renders the `article` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup article(String text);

  /// Renders the `aside` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup aside(Instruction... contents);

  /// Renders the `aside` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup aside(String text);

  /// Renders the `b` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup b(Instruction... contents);

  /// Renders the `b` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup b(String text);

  /// Renders the `blockquote` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup blockquote(Instruction... contents);

  /// Renders the `blockquote` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup blockquote(String text);

  /// Renders the `body` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup body(Instruction... contents);

  /// Renders the `body` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup body(String text);

  /// Renders the `br` element with the specified content.
  ///
  /// @param contents the attributes of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup br(Instruction.OfVoid... contents);

  /// Renders the `button` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup button(Instruction... contents);

  /// Renders the `button` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup button(String text);

  /// Renders the `clipPath` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup clipPath(Instruction... contents);

  /// Renders the `code` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup code(Instruction... contents);

  /// Renders the `code` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup code(String text);

  /// Renders the `dd` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup dd(Instruction... contents);

  /// Renders the `dd` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup dd(String text);

  /// Renders the `defs` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup defs(Instruction... contents);

  /// Renders the `defs` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup defs(String text);

  /// Renders the `details` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup details(Instruction... contents);

  /// Renders the `details` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup details(String text);

  /// Renders the `dialog` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup dialog(Instruction... contents);

  /// Renders the `dialog` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup dialog(String text);

  /// Renders the `div` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup div(Instruction... contents);

  /// Renders the `div` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup div(String text);

  /// Renders the `dl` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup dl(Instruction... contents);

  /// Renders the `dl` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup dl(String text);

  /// Renders the `dt` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup dt(Instruction... contents);

  /// Renders the `dt` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup dt(String text);

  /// Renders the `em` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup em(Instruction... contents);

  /// Renders the `em` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup em(String text);

  /// Renders the `fieldset` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup fieldset(Instruction... contents);

  /// Renders the `fieldset` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup fieldset(String text);

  /// Renders the `figure` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup figure(Instruction... contents);

  /// Renders the `figure` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup figure(String text);

  /// Renders the `footer` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup footer(Instruction... contents);

  /// Renders the `footer` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup footer(String text);

  /// Renders the `form` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup form(Instruction... contents);

  /// Renders the `g` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup g(Instruction... contents);

  /// Renders the `g` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup g(String text);

  /// Renders the `h1` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup h1(Instruction... contents);

  /// Renders the `h1` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup h1(String text);

  /// Renders the `h2` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup h2(Instruction... contents);

  /// Renders the `h2` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup h2(String text);

  /// Renders the `h3` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup h3(Instruction... contents);

  /// Renders the `h3` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup h3(String text);

  /// Renders the `h4` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup h4(Instruction... contents);

  /// Renders the `h4` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup h4(String text);

  /// Renders the `h5` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup h5(Instruction... contents);

  /// Renders the `h5` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup h5(String text);

  /// Renders the `h6` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup h6(Instruction... contents);

  /// Renders the `h6` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup h6(String text);

  /// Renders the `head` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup head(Instruction... contents);

  /// Renders the `head` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup head(String text);

  /// Renders the `header` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup header(Instruction... contents);

  /// Renders the `header` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup header(String text);

  /// Renders the `hgroup` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup hgroup(Instruction... contents);

  /// Renders the `hgroup` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup hgroup(String text);

  /// Renders the `hr` element with the specified content.
  ///
  /// @param contents the attributes of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup hr(Instruction.OfVoid... contents);

  /// Renders the `html` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup html(Instruction... contents);

  /// Renders the `html` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup html(String text);

  /// Renders the `img` element with the specified content.
  ///
  /// @param contents the attributes of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup img(Instruction.OfVoid... contents);

  /// Renders the `input` element with the specified content.
  ///
  /// @param contents the attributes of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup input(Instruction.OfVoid... contents);

  /// Renders the `kbd` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup kbd(Instruction... contents);

  /// Renders the `kbd` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup kbd(String text);

  /// Renders the `label` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup label(Instruction... contents);

  /// Renders the `legend` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup legend(Instruction... contents);

  /// Renders the `legend` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup legend(String text);

  /// Renders the `li` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup li(Instruction... contents);

  /// Renders the `li` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup li(String text);

  /// Renders the `link` element with the specified content.
  ///
  /// @param contents the attributes of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup link(Instruction.OfVoid... contents);

  /// Renders the `main` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup main(Instruction... contents);

  /// Renders the `main` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup main(String text);

  /// Renders the `menu` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup menu(Instruction... contents);

  /// Renders the `menu` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup menu(String text);

  /// Renders the `meta` element with the specified content.
  ///
  /// @param contents the attributes of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup meta(Instruction.OfVoid... contents);

  /// Renders the `nav` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup nav(Instruction... contents);

  /// Renders the `nav` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup nav(String text);

  /// Renders the `noscript` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup noscript(Instruction... contents);

  /// Renders the `noscript` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup noscript(String text);

  /// Renders the `ol` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup ol(Instruction... contents);

  /// Renders the `ol` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup ol(String text);

  /// Renders the `optgroup` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup optgroup(Instruction... contents);

  /// Renders the `optgroup` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup optgroup(String text);

  /// Renders the `option` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup option(Instruction... contents);

  /// Renders the `option` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup option(String text);

  /// Renders the `p` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup p(Instruction... contents);

  /// Renders the `p` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup p(String text);

  /// Renders the `path` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup path(Instruction... contents);

  /// Renders the `path` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup path(String text);

  /// Renders the `pre` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup pre(Instruction... contents);

  /// Renders the `pre` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup pre(String text);

  /// Renders the `progress` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup progress(Instruction... contents);

  /// Renders the `progress` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup progress(String text);

  /// Renders the `samp` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup samp(Instruction... contents);

  /// Renders the `samp` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup samp(String text);

  /// Renders the `script` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup script(Instruction... contents);

  /// Renders the `script` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup script(String text);

  /// Renders the `section` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup section(Instruction... contents);

  /// Renders the `section` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup section(String text);

  /// Renders the `select` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup select(Instruction... contents);

  /// Renders the `select` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup select(String text);

  /// Renders the `small` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup small(Instruction... contents);

  /// Renders the `small` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup small(String text);

  /// Renders the `span` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup span(Instruction... contents);

  /// Renders the `span` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup span(String text);

  /// Renders the `strong` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup strong(Instruction... contents);

  /// Renders the `strong` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup strong(String text);

  /// Renders the `style` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup style(Instruction... contents);

  /// Renders the `sub` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup sub(Instruction... contents);

  /// Renders the `sub` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup sub(String text);

  /// Renders the `summary` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup summary(Instruction... contents);

  /// Renders the `summary` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup summary(String text);

  /// Renders the `sup` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup sup(Instruction... contents);

  /// Renders the `sup` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup sup(String text);

  /// Renders the `svg` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup svg(Instruction... contents);

  /// Renders the `svg` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup svg(String text);

  /// Renders the `table` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup table(Instruction... contents);

  /// Renders the `table` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup table(String text);

  /// Renders the `tbody` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup tbody(Instruction... contents);

  /// Renders the `tbody` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup tbody(String text);

  /// Renders the `td` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup td(Instruction... contents);

  /// Renders the `td` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup td(String text);

  /// Renders the `template` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup template(Instruction... contents);

  /// Renders the `template` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup template(String text);

  /// Renders the `textarea` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup textarea(Instruction... contents);

  /// Renders the `textarea` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup textarea(String text);

  /// Renders the `th` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup th(Instruction... contents);

  /// Renders the `th` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup th(String text);

  /// Renders the `thead` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup thead(Instruction... contents);

  /// Renders the `thead` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup thead(String text);

  /// Renders the `title` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup title(Instruction... contents);

  /// Renders the `tr` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup tr(Instruction... contents);

  /// Renders the `tr` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup tr(String text);

  /// Renders the `ul` element with the specified content.
  ///
  /// @param contents the attributes and children of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup ul(Instruction... contents);

  /// Renders the `ul` element with the specified text.
  ///
  /// @param text the text value of the element
  ///
  /// @return an instruction representing the element.
  ElementMarkup ul(String text);

  //
  // ATTRIBUTES
  //

  /// Renders an attribute with the specified name.
  ///
  /// @param name the attribute name
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute attr(AttributeName name);

  /// Renders an attribute with the specified name and value.
  ///
  /// @param name the attribute name
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute attr(AttributeName name, String value);

  /// Renders the `accesskey` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute accesskey(String value);

  /// Renders the `action` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute action(String value);

  /// Renders the `align` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute align(String value);

  /// Renders the `alignment-baseline` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute alignmentBaseline(String value);

  /// Renders the `alt` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute alt(String value);

  /// Renders the `aria-current` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute ariaCurrent(String value);

  /// Renders the `aria-disabled` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute ariaDisabled(String value);

  /// Renders the `aria-hidden` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute ariaHidden(String value);

  /// Renders the `aria-invalid` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute ariaInvalid(String value);

  /// Renders the `aria-label` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute ariaLabel(String value);

  /// Renders the `aria-labelledby` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute ariaLabelledBy(String value);

  /// Renders the `aria-modal` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute ariaModal(String value);

  /// Renders the `aria-placeholder` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute ariaPlaceholder(String value);

  /// Renders the `aria-readonly` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute ariaReadonly(String value);

  /// Renders the `aria-required` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute ariaRequired(String value);

  /// Renders the `aria-selected` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute ariaSelected(String value);

  /// Renders the `as` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute as(String value);

  /// Renders the `autocomplete` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute autocomplete(String value);

  /// Renders the `baseline-shift` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute baselineShift(String value);

  /// Renders the `border` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute border(String value);

  /// Renders the `cellpadding` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute cellpadding(String value);

  /// Renders the `cellspacing` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute cellspacing(String value);

  /// Renders the `charset` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute charset(String value);

  /// Renders the `cite` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute cite(String value);

  /// Renders the `class` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute className(String value);

  /// Renders the `clip-rule` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute clipRule(String value);

  /// Renders the `closedby` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute closedby(String value);

  /// Renders the `color` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute color(String value);

  /// Renders the `color-interpolation` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute colorInterpolation(String value);

  /// Renders the `color-interpolation-filters` attribute with the specified
  /// value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute colorInterpolationFilters(String value);

  /// Renders the `cols` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute cols(String value);

  /// Renders the `content` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute content(String value);

  /// Renders the `contenteditable` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute contenteditable(String value);

  /// Renders the `crossorigin` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute crossorigin(String value);

  /// Renders the `cursor` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute cursor(String value);

  /// Renders the `d` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute d(String value);

  /// Renders the `dir` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute dir(String value);

  /// Renders the `direction` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute direction(String value);

  /// Renders the `dirname` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute dirname(String value);

  /// Renders the `display` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute display(String value);

  /// Renders the `dominant-baseline` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute dominantBaseline(String value);

  /// Renders the `download` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute download(String value);

  /// Renders the `draggable` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute draggable(String value);

  /// Renders the `enctype` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute enctype(String value);

  /// Renders the `fill` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute fill(String value);

  /// Renders the `fill-opacity` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute fillOpacity(String value);

  /// Renders the `fill-rule` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute fillRule(String value);

  /// Renders the `filter` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute filter(String value);

  /// Renders the `flood-color` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute floodColor(String value);

  /// Renders the `flood-opacity` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute floodOpacity(String value);

  /// Renders the `for` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute forId(String value);

  /// Renders the `glyph-orientation-horizontal` attribute with the specified
  /// value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute glyphOrientationHorizontal(String value);

  /// Renders the `glyph-orientation-vertical` attribute with the specified
  /// value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute glyphOrientationVertical(String value);

  /// Renders the `height` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute height(String value);

  /// Renders the `href` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute href(String value);

  /// Renders the `http-equiv` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute httpEquiv(String value);

  /// Renders the `id` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute id(String value);

  /// Renders the `image-rendering` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute imageRendering(String value);

  /// Renders the `integrity` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute integrity(String value);

  /// Renders the `lang` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute lang(String value);

  /// Renders the `letter-spacing` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute letterSpacing(String value);

  /// Renders the `lighting-color` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute lightingColor(String value);

  /// Renders the `marker-end` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute markerEnd(String value);

  /// Renders the `marker-mid` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute markerMid(String value);

  /// Renders the `marker-start` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute markerStart(String value);

  /// Renders the `mask` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute mask(String value);

  /// Renders the `mask-type` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute maskType(String value);

  /// Renders the `maxlength` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute maxlength(String value);

  /// Renders the `media` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute media(String value);

  /// Renders the `method` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute method(String value);

  /// Renders the `minlength` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute minlength(String value);

  /// Renders the `name` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute name(String value);

  /// Renders the `onclick` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute onclick(String value);

  /// Renders the `onclick` attribute with the specified action.
  ///
  /// @param value the action to be executed
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute onclick(JsAction value);

  /// Renders the `onload` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute onload(String value);

  /// Renders the `onload` attribute with the specified action.
  ///
  /// @param value the action to be executed
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute onload(JsAction value);

  /// Renders the `onpopstate` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute onpopstate(String value);

  /// Renders the `onpopstate` attribute with the specified action.
  ///
  /// @param value the action to be executed
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute onpopstate(JsAction value);

  /// Renders the `onsubmit` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute onsubmit(String value);

  /// Renders the `onsubmit` attribute with the specified action.
  ///
  /// @param value the action to be executed
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute onsubmit(JsAction value);

  /// Renders the `opacity` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute opacity(String value);

  /// Renders the `overflow` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute overflow(String value);

  /// Renders the `paint-order` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute paintOrder(String value);

  /// Renders the `placeholder` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute placeholder(String value);

  /// Renders the `pointer-events` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute pointerEvents(String value);

  /// Renders the `property` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute property(String value);

  /// Renders the `referrerpolicy` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute referrerpolicy(String value);

  /// Renders the `rel` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute rel(String value);

  /// Renders the `rev` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute rev(String value);

  /// Renders the `role` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute role(String value);

  /// Renders the `rows` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute rows(String value);

  /// Renders the `shape-rendering` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute shapeRendering(String value);

  /// Renders the `size` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute size(String value);

  /// Renders the `sizes` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute sizes(String value);

  /// Renders the `spellcheck` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute spellcheck(String value);

  /// Renders the `src` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute src(String value);

  /// Renders the `srcset` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute srcset(String value);

  /// Renders the `start` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute start(String value);

  /// Renders the `stop-color` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute stopColor(String value);

  /// Renders the `stop-opacity` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute stopOpacity(String value);

  /// Renders the `stroke` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute stroke(String value);

  /// Renders the `stroke-dasharray` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute strokeDasharray(String value);

  /// Renders the `stroke-dashoffset` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute strokeDashoffset(String value);

  /// Renders the `stroke-linecap` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute strokeLinecap(String value);

  /// Renders the `stroke-linejoin` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute strokeLinejoin(String value);

  /// Renders the `stroke-miterlimit` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute strokeMiterlimit(String value);

  /// Renders the `stroke-opacity` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute strokeOpacity(String value);

  /// Renders the `stroke-width` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute strokeWidth(String value);

  /// Renders the `tabindex` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute tabindex(String value);

  /// Renders the `target` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute target(String value);

  /// Renders the `text-anchor` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute textAnchor(String value);

  /// Renders the `text-decoration` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute textDecoration(String value);

  /// Renders the `text-overflow` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute textOverflow(String value);

  /// Renders the `text-rendering` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute textRendering(String value);

  /// Renders the `transform` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute transform(String value);

  /// Renders the `transform-origin` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute transformOrigin(String value);

  /// Renders the `translate` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute translate(String value);

  /// Renders the `type` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute type(String value);

  /// Renders the `unicode-bidi` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute unicodeBidi(String value);

  /// Renders the `value` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute value(String value);

  /// Renders the `vector-effect` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute vectorEffect(String value);

  /// Renders the `viewBox` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute viewBox(String value);

  /// Renders the `visibility` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute visibility(String value);

  /// Renders the `white-space` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute whiteSpace(String value);

  /// Renders the `width` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute width(String value);

  /// Renders the `word-spacing` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute wordSpacing(String value);

  /// Renders the `wrap` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute wrap(String value);

  /// Renders the `writing-mode` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute writingMode(String value);

  /// Renders the `xmlns` attribute with the specified value.
  ///
  /// @param value the attribute value
  ///
  /// @return an instruction representing the attribute
  Instruction.OfAttribute xmlns(String value);

  //
  // AMBIGUOUS
  //

  /// Renders the `clip-path` attribute or the `clipPath` element with the
  /// specified text.
  ///
  /// @param text the attribute value or the text content of the element
  ///
  /// @return an instruction representing the attribute or the element
  Instruction.OfAmbiguous clipPath(String text);

  /// Renders the `form` attribute or the `form` element with the specified
  /// text.
  ///
  /// @param text the attribute value or the text content of the element
  ///
  /// @return an instruction representing the attribute or the element
  Instruction.OfAmbiguous form(String text);

  /// Renders the `label` attribute or the `label` element with the specified
  /// text.
  ///
  /// @param text the attribute value or the text content of the element
  ///
  /// @return an instruction representing the attribute or the element
  Instruction.OfAmbiguous label(String text);

  /// Renders the `style` attribute or the `style` element with the specified
  /// text.
  ///
  /// @param text the attribute value or the text content of the element
  ///
  /// @return an instruction representing the attribute or the element
  Instruction.OfAmbiguous style(String text);

  /// Renders the `title` attribute or the `title` element with the specified
  /// text.
  ///
  /// @param text the attribute value or the text content of the element
  ///
  /// @return an instruction representing the attribute or the element
  Instruction.OfAmbiguous title(String text);

  //
  // TEXT
  //

  /// Renders the non-breaking space `&nbsp;` HTML character entity.
  ///
  /// @return an instruction representing the non-breaking space
  ///         character entity.
  ElementMarkup nbsp();

  /// Renders the specified value as raw HTML.
  ///
  /// @param value the raw HTML value
  ///
  /// @return a raw HTML instruction
  ElementMarkup raw(String value);

  /// Renders a text node with the specified value. The text value is escaped
  /// before being emitted to the output.
  ///
  /// @param value the text value
  ///
  /// @return an instruction representing the text node
  ElementMarkup text(String value);

  // END generated code

}