/*
 * Copyright (C) 2015-2024 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.html;

/**
 * Provides methods for rendering HTML attributes in templates.
 */
// Generated by objectos.selfgen.HtmlSpec. Do not edit!
public sealed abstract class TemplateAttributes permits TemplateElements {
  TemplateAttributes() {}

  /**
   * Generates the {@code accesskey} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlobalAttribute accesskey(String value) {
    return $html().accesskey(value);
  }

  /**
   * Generates the {@code action} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.FormValue action(String value) {
    return $html().action(value);
  }

  /**
   * Generates the {@code align} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TableValue align(String value) {
    return $html().align(value);
  }

  /**
   * Generates the {@code alignment-baseline} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.AlignmentBaselineAttribute alignmentBaseline(String value) {
    return $html().alignmentBaseline(value);
  }

  /**
   * Generates the {@code alt} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.ImageValue alt(String value) {
    return $html().alt(value);
  }

  /**
   * Generates the {@code aria-hidden} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlobalAttribute ariaHidden(String value) {
    return $html().ariaHidden(value);
  }

  /**
   * Generates the {@code aria-label} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlobalAttribute ariaLabel(String value) {
    return $html().ariaLabel(value);
  }

  /**
   * Generates the {@code async} boolean attribute.
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.ScriptValue async() {
    return $html().async();
  }

  /**
   * Generates the {@code autocomplete} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.AutocompleteAttribute autocomplete(String value) {
    return $html().autocomplete(value);
  }

  /**
   * Generates the {@code autofocus} boolean attribute.
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.InputValue autofocus() {
    return $html().autofocus();
  }

  /**
   * Generates the {@code baseline-shift} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.BaselineShiftAttribute baselineShift(String value) {
    return $html().baselineShift(value);
  }

  /**
   * Generates the {@code border} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TableValue border(String value) {
    return $html().border(value);
  }

  /**
   * Generates the {@code cellpadding} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TableValue cellpadding(String value) {
    return $html().cellpadding(value);
  }

  /**
   * Generates the {@code cellspacing} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TableValue cellspacing(String value) {
    return $html().cellspacing(value);
  }

  /**
   * Generates the {@code charset} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.MetaValue charset(String value) {
    return $html().charset(value);
  }

  /**
   * Generates the {@code cite} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.BlockquoteValue cite(String value) {
    return $html().cite(value);
  }

  /**
   * Generates the {@code class} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlobalAttribute className(String value) {
    return $html().className(value);
  }

  /**
   * Generates the {@code clip-rule} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.ClipRuleAttribute clipRule(String value) {
    return $html().clipRule(value);
  }

  /**
   * Generates the {@code color} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.ColorAttribute color(String value) {
    return $html().color(value);
  }

  /**
   * Generates the {@code color-interpolation} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.ColorInterpolationAttribute colorInterpolation(String value) {
    return $html().colorInterpolation(value);
  }

  /**
   * Generates the {@code color-interpolation-filters} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.ColorInterpolationFiltersAttribute colorInterpolationFilters(String value) {
    return $html().colorInterpolationFilters(value);
  }

  /**
   * Generates the {@code cols} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TextAreaValue cols(String value) {
    return $html().cols(value);
  }

  /**
   * Generates the {@code content} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.MetaValue content(String value) {
    return $html().content(value);
  }

  /**
   * Generates the {@code contenteditable} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlobalAttribute contenteditable(String value) {
    return $html().contenteditable(value);
  }

  /**
   * Generates the {@code crossorigin} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.CrossoriginAttribute crossorigin(String value) {
    return $html().crossorigin(value);
  }

  /**
   * Generates the {@code cursor} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.CursorAttribute cursor(String value) {
    return $html().cursor(value);
  }

  /**
   * Generates the {@code d} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.DAttribute d(String value) {
    return $html().d(value);
  }

  /**
   * Generates the {@code defer} boolean attribute.
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.ScriptValue defer() {
    return $html().defer();
  }

  /**
   * Generates the {@code dir} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlobalAttribute dir(String value) {
    return $html().dir(value);
  }

  /**
   * Generates the {@code direction} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.DirectionAttribute direction(String value) {
    return $html().direction(value);
  }

  /**
   * Generates the {@code dirname} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TextAreaValue dirname(String value) {
    return $html().dirname(value);
  }

  /**
   * Generates the {@code disabled} boolean attribute.
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.DisabledAttribute disabled() {
    return $html().disabled();
  }

  /**
   * Generates the {@code display} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.DisplayAttribute display(String value) {
    return $html().display(value);
  }

  /**
   * Generates the {@code dominant-baseline} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.DominantBaselineAttribute dominantBaseline(String value) {
    return $html().dominantBaseline(value);
  }

  /**
   * Generates the {@code draggable} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlobalAttribute draggable(String value) {
    return $html().draggable(value);
  }

  /**
   * Generates the {@code enctype} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.FormValue enctype(String value) {
    return $html().enctype(value);
  }

  /**
   * Generates the {@code fill} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.FillAttribute fill(String value) {
    return $html().fill(value);
  }

  /**
   * Generates the {@code fill-opacity} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.FillOpacityAttribute fillOpacity(String value) {
    return $html().fillOpacity(value);
  }

  /**
   * Generates the {@code fill-rule} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.FillRuleAttribute fillRule(String value) {
    return $html().fillRule(value);
  }

  /**
   * Generates the {@code filter} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.FilterAttribute filter(String value) {
    return $html().filter(value);
  }

  /**
   * Generates the {@code flood-color} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.FloodColorAttribute floodColor(String value) {
    return $html().floodColor(value);
  }

  /**
   * Generates the {@code flood-opacity} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.FloodOpacityAttribute floodOpacity(String value) {
    return $html().floodOpacity(value);
  }

  /**
   * Generates the {@code font-family} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.FontFamilyAttribute fontFamily(String value) {
    return $html().fontFamily(value);
  }

  /**
   * Generates the {@code font-size} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.FontSizeAttribute fontSize(String value) {
    return $html().fontSize(value);
  }

  /**
   * Generates the {@code font-size-adjust} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.FontSizeAdjustAttribute fontSizeAdjust(String value) {
    return $html().fontSizeAdjust(value);
  }

  /**
   * Generates the {@code font-stretch} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.FontStretchAttribute fontStretch(String value) {
    return $html().fontStretch(value);
  }

  /**
   * Generates the {@code font-style} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.FontStyleAttribute fontStyle(String value) {
    return $html().fontStyle(value);
  }

  /**
   * Generates the {@code font-variant} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.FontVariantAttribute fontVariant(String value) {
    return $html().fontVariant(value);
  }

  /**
   * Generates the {@code font-weight} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.FontWeightAttribute fontWeight(String value) {
    return $html().fontWeight(value);
  }

  /**
   * Generates the {@code for} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.LabelValue forAttr(String value) {
    return $html().forAttr(value);
  }

  /**
   * Generates the {@code for} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.LabelValue forElement(String value) {
    return $html().forElement(value);
  }

  /**
   * Generates the {@code glyph-orientation-horizontal} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlyphOrientationHorizontalAttribute glyphOrientationHorizontal(String value) {
    return $html().glyphOrientationHorizontal(value);
  }

  /**
   * Generates the {@code glyph-orientation-vertical} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlyphOrientationVerticalAttribute glyphOrientationVertical(String value) {
    return $html().glyphOrientationVertical(value);
  }

  /**
   * Generates the {@code height} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.HeightAttribute height(String value) {
    return $html().height(value);
  }

  /**
   * Generates the {@code hidden} boolean attribute.
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlobalAttribute hidden() {
    return $html().hidden();
  }

  /**
   * Generates the {@code href} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.HrefAttribute href(String value) {
    return $html().href(value);
  }

  /**
   * Generates the {@code http-equiv} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.MetaValue httpEquiv(String value) {
    return $html().httpEquiv(value);
  }

  /**
   * Generates the {@code id} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlobalAttribute id(String value) {
    return $html().id(value);
  }

  /**
   * Generates the {@code image-rendering} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.ImageRenderingAttribute imageRendering(String value) {
    return $html().imageRendering(value);
  }

  /**
   * Generates the {@code integrity} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.ScriptValue integrity(String value) {
    return $html().integrity(value);
  }

  /**
   * Generates the {@code lang} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlobalAttribute lang(String value) {
    return $html().lang(value);
  }

  /**
   * Generates the {@code letter-spacing} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.LetterSpacingAttribute letterSpacing(String value) {
    return $html().letterSpacing(value);
  }

  /**
   * Generates the {@code lighting-color} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.LightingColorAttribute lightingColor(String value) {
    return $html().lightingColor(value);
  }

  /**
   * Generates the {@code marker-end} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.MarkerEndAttribute markerEnd(String value) {
    return $html().markerEnd(value);
  }

  /**
   * Generates the {@code marker-mid} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.MarkerMidAttribute markerMid(String value) {
    return $html().markerMid(value);
  }

  /**
   * Generates the {@code marker-start} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.MarkerStartAttribute markerStart(String value) {
    return $html().markerStart(value);
  }

  /**
   * Generates the {@code mask} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.MaskAttribute mask(String value) {
    return $html().mask(value);
  }

  /**
   * Generates the {@code mask-type} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.MaskTypeAttribute maskType(String value) {
    return $html().maskType(value);
  }

  /**
   * Generates the {@code maxlength} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TextAreaValue maxlength(String value) {
    return $html().maxlength(value);
  }

  /**
   * Generates the {@code media} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.LinkValue media(String value) {
    return $html().media(value);
  }

  /**
   * Generates the {@code method} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.FormValue method(String value) {
    return $html().method(value);
  }

  /**
   * Generates the {@code minlength} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TextAreaValue minlength(String value) {
    return $html().minlength(value);
  }

  /**
   * Generates the {@code multiple} boolean attribute.
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.SelectValue multiple() {
    return $html().multiple();
  }

  /**
   * Generates the {@code name} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.NameAttribute name(String value) {
    return $html().name(value);
  }

  /**
   * Generates the {@code nomodule} boolean attribute.
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.ScriptValue nomodule() {
    return $html().nomodule();
  }

  /**
   * Generates the {@code onafterprint} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.BodyValue onafterprint(String value) {
    return $html().onafterprint(value);
  }

  /**
   * Generates the {@code onbeforeprint} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.BodyValue onbeforeprint(String value) {
    return $html().onbeforeprint(value);
  }

  /**
   * Generates the {@code onbeforeunload} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.BodyValue onbeforeunload(String value) {
    return $html().onbeforeunload(value);
  }

  /**
   * Generates the {@code onclick} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlobalAttribute onclick(String value) {
    return $html().onclick(value);
  }

  /**
   * Generates the {@code onhashchange} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.BodyValue onhashchange(String value) {
    return $html().onhashchange(value);
  }

  /**
   * Generates the {@code onlanguagechange} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.BodyValue onlanguagechange(String value) {
    return $html().onlanguagechange(value);
  }

  /**
   * Generates the {@code onmessage} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.BodyValue onmessage(String value) {
    return $html().onmessage(value);
  }

  /**
   * Generates the {@code onoffline} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.BodyValue onoffline(String value) {
    return $html().onoffline(value);
  }

  /**
   * Generates the {@code ononline} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.BodyValue ononline(String value) {
    return $html().ononline(value);
  }

  /**
   * Generates the {@code onpagehide} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.BodyValue onpagehide(String value) {
    return $html().onpagehide(value);
  }

  /**
   * Generates the {@code onpageshow} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.BodyValue onpageshow(String value) {
    return $html().onpageshow(value);
  }

  /**
   * Generates the {@code onpopstate} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.BodyValue onpopstate(String value) {
    return $html().onpopstate(value);
  }

  /**
   * Generates the {@code onrejectionhandled} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.BodyValue onrejectionhandled(String value) {
    return $html().onrejectionhandled(value);
  }

  /**
   * Generates the {@code onstorage} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.BodyValue onstorage(String value) {
    return $html().onstorage(value);
  }

  /**
   * Generates the {@code onsubmit} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlobalAttribute onsubmit(String value) {
    return $html().onsubmit(value);
  }

  /**
   * Generates the {@code onunhandledrejection} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.BodyValue onunhandledrejection(String value) {
    return $html().onunhandledrejection(value);
  }

  /**
   * Generates the {@code onunload} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.BodyValue onunload(String value) {
    return $html().onunload(value);
  }

  /**
   * Generates the {@code opacity} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.OpacityAttribute opacity(String value) {
    return $html().opacity(value);
  }

  /**
   * Generates the {@code open} boolean attribute.
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.DetailsValue open() {
    return $html().open();
  }

  /**
   * Generates the {@code overflow} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.OverflowAttribute overflow(String value) {
    return $html().overflow(value);
  }

  /**
   * Generates the {@code paint-order} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.PaintOrderAttribute paintOrder(String value) {
    return $html().paintOrder(value);
  }

  /**
   * Generates the {@code placeholder} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.PlaceholderAttribute placeholder(String value) {
    return $html().placeholder(value);
  }

  /**
   * Generates the {@code pointer-events} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.PointerEventsAttribute pointerEvents(String value) {
    return $html().pointerEvents(value);
  }

  /**
   * Generates the {@code property} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.MetaValue property(String value) {
    return $html().property(value);
  }

  /**
   * Generates the {@code readonly} boolean attribute.
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.ReadonlyAttribute readonly() {
    return $html().readonly();
  }

  /**
   * Generates the {@code referrerpolicy} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.ReferrerpolicyAttribute referrerpolicy(String value) {
    return $html().referrerpolicy(value);
  }

  /**
   * Generates the {@code rel} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.LinkValue rel(String value) {
    return $html().rel(value);
  }

  /**
   * Generates the {@code required} boolean attribute.
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.RequiredAttribute required() {
    return $html().required();
  }

  /**
   * Generates the {@code rev} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.LinkValue rev(String value) {
    return $html().rev(value);
  }

  /**
   * Generates the {@code reversed} boolean attribute.
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.OrderedListValue reversed() {
    return $html().reversed();
  }

  /**
   * Generates the {@code role} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlobalAttribute role(String value) {
    return $html().role(value);
  }

  /**
   * Generates the {@code rows} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TextAreaValue rows(String value) {
    return $html().rows(value);
  }

  /**
   * Generates the {@code selected} boolean attribute.
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.OptionValue selected() {
    return $html().selected();
  }

  /**
   * Generates the {@code shape-rendering} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.ShapeRenderingAttribute shapeRendering(String value) {
    return $html().shapeRendering(value);
  }

  /**
   * Generates the {@code size} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.SelectValue size(String value) {
    return $html().size(value);
  }

  /**
   * Generates the {@code sizes} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.LinkValue sizes(String value) {
    return $html().sizes(value);
  }

  /**
   * Generates the {@code spellcheck} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlobalAttribute spellcheck(String value) {
    return $html().spellcheck(value);
  }

  /**
   * Generates the {@code src} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.SrcAttribute src(String value) {
    return $html().src(value);
  }

  /**
   * Generates the {@code srcset} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.ImageValue srcset(String value) {
    return $html().srcset(value);
  }

  /**
   * Generates the {@code start} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.OrderedListValue start(String value) {
    return $html().start(value);
  }

  /**
   * Generates the {@code stop-color} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.StopColorAttribute stopColor(String value) {
    return $html().stopColor(value);
  }

  /**
   * Generates the {@code stop-opacity} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.StopOpacityAttribute stopOpacity(String value) {
    return $html().stopOpacity(value);
  }

  /**
   * Generates the {@code stroke} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.StrokeAttribute stroke(String value) {
    return $html().stroke(value);
  }

  /**
   * Generates the {@code stroke-dasharray} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.StrokeDasharrayAttribute strokeDasharray(String value) {
    return $html().strokeDasharray(value);
  }

  /**
   * Generates the {@code stroke-dashoffset} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.StrokeDashoffsetAttribute strokeDashoffset(String value) {
    return $html().strokeDashoffset(value);
  }

  /**
   * Generates the {@code stroke-linecap} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.StrokeLinecapAttribute strokeLinecap(String value) {
    return $html().strokeLinecap(value);
  }

  /**
   * Generates the {@code stroke-linejoin} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.StrokeLinejoinAttribute strokeLinejoin(String value) {
    return $html().strokeLinejoin(value);
  }

  /**
   * Generates the {@code stroke-miterlimit} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.StrokeMiterlimitAttribute strokeMiterlimit(String value) {
    return $html().strokeMiterlimit(value);
  }

  /**
   * Generates the {@code stroke-opacity} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.StrokeOpacityAttribute strokeOpacity(String value) {
    return $html().strokeOpacity(value);
  }

  /**
   * Generates the {@code stroke-width} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.StrokeWidthAttribute strokeWidth(String value) {
    return $html().strokeWidth(value);
  }

  /**
   * Generates the {@code style} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlobalAttribute inlineStyle(String value) {
    return $html().inlineStyle(value);
  }

  /**
   * Generates the {@code tabindex} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlobalAttribute tabindex(String value) {
    return $html().tabindex(value);
  }

  /**
   * Generates the {@code target} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TargetAttribute target(String value) {
    return $html().target(value);
  }

  /**
   * Generates the {@code text-anchor} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TextAnchorAttribute textAnchor(String value) {
    return $html().textAnchor(value);
  }

  /**
   * Generates the {@code text-decoration} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TextDecorationAttribute textDecoration(String value) {
    return $html().textDecoration(value);
  }

  /**
   * Generates the {@code text-overflow} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TextOverflowAttribute textOverflow(String value) {
    return $html().textOverflow(value);
  }

  /**
   * Generates the {@code text-rendering} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TextRenderingAttribute textRendering(String value) {
    return $html().textRendering(value);
  }

  /**
   * Generates the {@code transform} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TransformAttribute transform(String value) {
    return $html().transform(value);
  }

  /**
   * Generates the {@code transform-origin} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TransformOriginAttribute transformOrigin(String value) {
    return $html().transformOrigin(value);
  }

  /**
   * Generates the {@code translate} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.GlobalAttribute translate(String value) {
    return $html().translate(value);
  }

  /**
   * Generates the {@code type} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TypeAttribute type(String value) {
    return $html().type(value);
  }

  /**
   * Generates the {@code unicode-bidi} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.UnicodeBidiAttribute unicodeBidi(String value) {
    return $html().unicodeBidi(value);
  }

  /**
   * Generates the {@code value} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.ValueAttribute value(String value) {
    return $html().value(value);
  }

  /**
   * Generates the {@code vector-effect} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.VectorEffectAttribute vectorEffect(String value) {
    return $html().vectorEffect(value);
  }

  /**
   * Generates the {@code viewBox} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.SvgValue viewBox(String value) {
    return $html().viewBox(value);
  }

  /**
   * Generates the {@code visibility} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.VisibilityAttribute visibility(String value) {
    return $html().visibility(value);
  }

  /**
   * Generates the {@code white-space} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.WhiteSpaceAttribute whiteSpace(String value) {
    return $html().whiteSpace(value);
  }

  /**
   * Generates the {@code width} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.WidthAttribute width(String value) {
    return $html().width(value);
  }

  /**
   * Generates the {@code word-spacing} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.WordSpacingAttribute wordSpacing(String value) {
    return $html().wordSpacing(value);
  }

  /**
   * Generates the {@code wrap} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.TextAreaValue wrap(String value) {
    return $html().wrap(value);
  }

  /**
   * Generates the {@code writing-mode} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.WritingModeAttribute writingMode(String value) {
    return $html().writingMode(value);
  }

  /**
   * Generates the {@code xmlns} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.SvgValue xmlns(String value) {
    return $html().xmlns(value);
  }

  /**
   * Generates the {@code clip-path} attribute with the specified value.
   *
   * @param value
   *        the value of the attribute
   *
   * @return an instruction representing this attribute.
   */
  protected final Api.ClipPathAttribute clipPath(String value) {
    return $html().clipPath(value);
  }

  abstract Html $html();
}
