/*
 * Copyright (C) 2015-2023 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.html.internal;

import objectos.html.tmpl.Api.AlignmentBaselineAttribute;
import objectos.html.tmpl.Api.AmbiguousInstruction;
import objectos.html.tmpl.Api.AutocompleteAttribute;
import objectos.html.tmpl.Api.BaselineShiftAttribute;
import objectos.html.tmpl.Api.ClipPathAttribute;
import objectos.html.tmpl.Api.ClipRuleAttribute;
import objectos.html.tmpl.Api.ColorAttribute;
import objectos.html.tmpl.Api.ColorInterpolationAttribute;
import objectos.html.tmpl.Api.ColorInterpolationFiltersAttribute;
import objectos.html.tmpl.Api.CrossoriginAttribute;
import objectos.html.tmpl.Api.CursorAttribute;
import objectos.html.tmpl.Api.DAttribute;
import objectos.html.tmpl.Api.DirectionAttribute;
import objectos.html.tmpl.Api.DisabledAttribute;
import objectos.html.tmpl.Api.DisplayAttribute;
import objectos.html.tmpl.Api.DominantBaselineAttribute;
import objectos.html.tmpl.Api.ElementContents;
import objectos.html.tmpl.Api.FillAttribute;
import objectos.html.tmpl.Api.FillOpacityAttribute;
import objectos.html.tmpl.Api.FillRuleAttribute;
import objectos.html.tmpl.Api.FilterAttribute;
import objectos.html.tmpl.Api.FloodColorAttribute;
import objectos.html.tmpl.Api.FloodOpacityAttribute;
import objectos.html.tmpl.Api.FontFamilyAttribute;
import objectos.html.tmpl.Api.FontSizeAdjustAttribute;
import objectos.html.tmpl.Api.FontSizeAttribute;
import objectos.html.tmpl.Api.FontStretchAttribute;
import objectos.html.tmpl.Api.FontStyleAttribute;
import objectos.html.tmpl.Api.FontVariantAttribute;
import objectos.html.tmpl.Api.FontWeightAttribute;
import objectos.html.tmpl.Api.FormAttribute;
import objectos.html.tmpl.Api.GlobalAttribute;
import objectos.html.tmpl.Api.GlyphOrientationHorizontalAttribute;
import objectos.html.tmpl.Api.GlyphOrientationVerticalAttribute;
import objectos.html.tmpl.Api.HeightAttribute;
import objectos.html.tmpl.Api.HrefAttribute;
import objectos.html.tmpl.Api.ImageRenderingAttribute;
import objectos.html.tmpl.Api.LetterSpacingAttribute;
import objectos.html.tmpl.Api.LightingColorAttribute;
import objectos.html.tmpl.Api.MarkerEndAttribute;
import objectos.html.tmpl.Api.MarkerMidAttribute;
import objectos.html.tmpl.Api.MarkerStartAttribute;
import objectos.html.tmpl.Api.MaskAttribute;
import objectos.html.tmpl.Api.MaskTypeAttribute;
import objectos.html.tmpl.Api.NameAttribute;
import objectos.html.tmpl.Api.OpacityAttribute;
import objectos.html.tmpl.Api.OverflowAttribute;
import objectos.html.tmpl.Api.PaintOrderAttribute;
import objectos.html.tmpl.Api.PlaceholderAttribute;
import objectos.html.tmpl.Api.PointerEventsAttribute;
import objectos.html.tmpl.Api.ReadonlyAttribute;
import objectos.html.tmpl.Api.ReferrerpolicyAttribute;
import objectos.html.tmpl.Api.RequiredAttribute;
import objectos.html.tmpl.Api.ShapeRenderingAttribute;
import objectos.html.tmpl.Api.SrcAttribute;
import objectos.html.tmpl.Api.StopColorAttribute;
import objectos.html.tmpl.Api.StopOpacityAttribute;
import objectos.html.tmpl.Api.StrokeAttribute;
import objectos.html.tmpl.Api.StrokeDasharrayAttribute;
import objectos.html.tmpl.Api.StrokeDashoffsetAttribute;
import objectos.html.tmpl.Api.StrokeLinecapAttribute;
import objectos.html.tmpl.Api.StrokeLinejoinAttribute;
import objectos.html.tmpl.Api.StrokeMiterlimitAttribute;
import objectos.html.tmpl.Api.StrokeOpacityAttribute;
import objectos.html.tmpl.Api.StrokeWidthAttribute;
import objectos.html.tmpl.Api.TargetAttribute;
import objectos.html.tmpl.Api.TextAnchorAttribute;
import objectos.html.tmpl.Api.TextDecorationAttribute;
import objectos.html.tmpl.Api.TextOverflowAttribute;
import objectos.html.tmpl.Api.TextRenderingAttribute;
import objectos.html.tmpl.Api.TransformAttribute;
import objectos.html.tmpl.Api.TransformOriginAttribute;
import objectos.html.tmpl.Api.TypeAttribute;
import objectos.html.tmpl.Api.UnicodeBidiAttribute;
import objectos.html.tmpl.Api.ValueAttribute;
import objectos.html.tmpl.Api.VectorEffectAttribute;
import objectos.html.tmpl.Api.VisibilityAttribute;
import objectos.html.tmpl.Api.WhiteSpaceAttribute;
import objectos.html.tmpl.Api.WidthAttribute;
import objectos.html.tmpl.Api.WordSpacingAttribute;
import objectos.html.tmpl.Api.WritingModeAttribute;

/**
 * TODO
 */
// Generated by selfgen.html.HtmlSpec. Do not edit!
public enum InternalInstruction implements
    AlignmentBaselineAttribute,
    AutocompleteAttribute,
    BaselineShiftAttribute,
    ClipPathAttribute,
    ClipRuleAttribute,
    ColorAttribute,
    ColorInterpolationAttribute,
    ColorInterpolationFiltersAttribute,
    CrossoriginAttribute,
    CursorAttribute,
    DAttribute,
    DirectionAttribute,
    DisabledAttribute,
    DisplayAttribute,
    DominantBaselineAttribute,
    FillAttribute,
    FillOpacityAttribute,
    FillRuleAttribute,
    FilterAttribute,
    FloodColorAttribute,
    FloodOpacityAttribute,
    FontFamilyAttribute,
    FontSizeAttribute,
    FontSizeAdjustAttribute,
    FontStretchAttribute,
    FontStyleAttribute,
    FontVariantAttribute,
    FontWeightAttribute,
    FormAttribute,
    GlyphOrientationHorizontalAttribute,
    GlyphOrientationVerticalAttribute,
    HeightAttribute,
    HrefAttribute,
    ImageRenderingAttribute,
    LetterSpacingAttribute,
    LightingColorAttribute,
    MarkerEndAttribute,
    MarkerMidAttribute,
    MarkerStartAttribute,
    MaskAttribute,
    MaskTypeAttribute,
    NameAttribute,
    OpacityAttribute,
    OverflowAttribute,
    PaintOrderAttribute,
    PlaceholderAttribute,
    PointerEventsAttribute,
    ReadonlyAttribute,
    ReferrerpolicyAttribute,
    RequiredAttribute,
    ShapeRenderingAttribute,
    SrcAttribute,
    StopColorAttribute,
    StopOpacityAttribute,
    StrokeAttribute,
    StrokeDasharrayAttribute,
    StrokeDashoffsetAttribute,
    StrokeLinecapAttribute,
    StrokeLinejoinAttribute,
    StrokeMiterlimitAttribute,
    StrokeOpacityAttribute,
    StrokeWidthAttribute,
    TargetAttribute,
    TextAnchorAttribute,
    TextDecorationAttribute,
    TextOverflowAttribute,
    TextRenderingAttribute,
    TransformAttribute,
    TransformOriginAttribute,
    TypeAttribute,
    UnicodeBidiAttribute,
    ValueAttribute,
    VectorEffectAttribute,
    VisibilityAttribute,
    WhiteSpaceAttribute,
    WidthAttribute,
    WordSpacingAttribute,
    WritingModeAttribute,

    AmbiguousInstruction,
    GlobalAttribute,
    ElementContents {
  INSTANCE;
}
