'
' Copyright (C) 2020-2023 Objectos Software LTDA.
'
' Licensed under the Apache License, Version 2.0 (the "License");
' you may not use this file except in compliance with the License.
' You may obtain a copy of the License at
'
' http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law or agreed to in writing, software
' distributed under the License is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
' See the License for the specific language governing permissions and
' limitations under the License.
'

@startuml

hide empty description
skinparam shadowing false

[*] --> START

CREATE_IO_EXCEPTION --> FINALLY

FetchCommitTask : defined on its own file
FetchCommitTask --> CREATE_IO_EXCEPTION
FetchCommitTask --> RESULT

FINALLY --> [*] : adapter.close()\lobjectChannel.close()

HEADER --> FetchCommitTask
HEADER --> FINALLY : CorruptObjectDatabaseException\leg: fetch commit found blob\leg: no header

INFLATE --> HEADER : adapter.inflate()
INFLATE --> FINALLY : IOException

IO --> IO_WAIT : execute(ioCommand)

IO_WAIT --> INFLATE : ioReady
IO_WAIT --> READ_OBJECT : ioReady
IO_WAIT --> FINALLY : IOException
IO_WAIT --> CREATE_IO_EXCEPTION : TimeoutException
IO_WAIT --> IO_WAIT : wait some more

OPEN_OBJECT --> IO : inflateAction = HEADER\lioKind = OPEN_OBJECT\lioReady = READ_OBJECT
OPEN_OBJECT --> FINALLY : ObjectNotFoundException

READ_OBJECT --> IO : ioKind = READ_OBJECT\lioReady = INFLATE

RESULT --> FINALLY : executeResult()

START --> OPEN_OBJECT : adapter.reset()\lcharset = utf8

@enduml