/*
 * Copyright (C) 2015-2023 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.html;

import objectos.html.internal.Ambiguous;
import objectos.html.internal.StandardElementName;
import objectos.html.tmpl.Api;
import objectos.html.tmpl.Api.AbbreviationInstruction;
import objectos.html.tmpl.Api.AnchorInstruction;
import objectos.html.tmpl.Api.ArticleInstruction;
import objectos.html.tmpl.Api.BlockquoteInstruction;
import objectos.html.tmpl.Api.BodyInstruction;
import objectos.html.tmpl.Api.BringAttentionToInstruction;
import objectos.html.tmpl.Api.ButtonInstruction;
import objectos.html.tmpl.Api.ClipPathInstruction;
import objectos.html.tmpl.Api.CodeInstruction;
import objectos.html.tmpl.Api.DefinitionDescriptionInstruction;
import objectos.html.tmpl.Api.DefinitionListInstruction;
import objectos.html.tmpl.Api.DefinitionTermInstruction;
import objectos.html.tmpl.Api.DefsInstruction;
import objectos.html.tmpl.Api.DetailsInstruction;
import objectos.html.tmpl.Api.DivInstruction;
import objectos.html.tmpl.Api.ElementContents;
import objectos.html.tmpl.Api.EmphasisInstruction;
import objectos.html.tmpl.Api.FieldsetInstruction;
import objectos.html.tmpl.Api.FigureInstruction;
import objectos.html.tmpl.Api.FooterInstruction;
import objectos.html.tmpl.Api.FormInstruction;
import objectos.html.tmpl.Api.GInstruction;
import objectos.html.tmpl.Api.HeadInstruction;
import objectos.html.tmpl.Api.HeaderInstruction;
import objectos.html.tmpl.Api.Heading1Instruction;
import objectos.html.tmpl.Api.Heading2Instruction;
import objectos.html.tmpl.Api.Heading3Instruction;
import objectos.html.tmpl.Api.Heading4Instruction;
import objectos.html.tmpl.Api.Heading5Instruction;
import objectos.html.tmpl.Api.Heading6Instruction;
import objectos.html.tmpl.Api.HeadingGroupInstruction;
import objectos.html.tmpl.Api.HorizontalRuleInstruction;
import objectos.html.tmpl.Api.HtmlInstruction;
import objectos.html.tmpl.Api.ImageInstruction;
import objectos.html.tmpl.Api.InputInstruction;
import objectos.html.tmpl.Api.Instruction;
import objectos.html.tmpl.Api.KeyboardInputInstruction;
import objectos.html.tmpl.Api.LabelInstruction;
import objectos.html.tmpl.Api.LegendInstruction;
import objectos.html.tmpl.Api.LineBreakInstruction;
import objectos.html.tmpl.Api.LinkInstruction;
import objectos.html.tmpl.Api.ListItemInstruction;
import objectos.html.tmpl.Api.MainInstruction;
import objectos.html.tmpl.Api.MenuInstruction;
import objectos.html.tmpl.Api.MetaInstruction;
import objectos.html.tmpl.Api.NavInstruction;
import objectos.html.tmpl.Api.OptionGroupInstruction;
import objectos.html.tmpl.Api.OptionInstruction;
import objectos.html.tmpl.Api.OrderedListInstruction;
import objectos.html.tmpl.Api.ParagraphInstruction;
import objectos.html.tmpl.Api.PathInstruction;
import objectos.html.tmpl.Api.PreInstruction;
import objectos.html.tmpl.Api.ProgressInstruction;
import objectos.html.tmpl.Api.SampleOutputInstruction;
import objectos.html.tmpl.Api.ScriptInstruction;
import objectos.html.tmpl.Api.SectionInstruction;
import objectos.html.tmpl.Api.SelectInstruction;
import objectos.html.tmpl.Api.SmallInstruction;
import objectos.html.tmpl.Api.SpanInstruction;
import objectos.html.tmpl.Api.StrongInstruction;
import objectos.html.tmpl.Api.StyleInstruction;
import objectos.html.tmpl.Api.SubscriptInstruction;
import objectos.html.tmpl.Api.SummaryInstruction;
import objectos.html.tmpl.Api.SuperscriptInstruction;
import objectos.html.tmpl.Api.SvgInstruction;
import objectos.html.tmpl.Api.TableBodyInstruction;
import objectos.html.tmpl.Api.TableDataInstruction;
import objectos.html.tmpl.Api.TableHeadInstruction;
import objectos.html.tmpl.Api.TableHeaderInstruction;
import objectos.html.tmpl.Api.TableInstruction;
import objectos.html.tmpl.Api.TableRowInstruction;
import objectos.html.tmpl.Api.TemplateInstruction;
import objectos.html.tmpl.Api.TextAreaInstruction;
import objectos.html.tmpl.Api.TitleInstruction;
import objectos.html.tmpl.Api.UnorderedListInstruction;

/**
 * Provides methods for rendering HTML elements.
 */
// Generated by selfgen.html.HtmlSpec. Do not edit!
public sealed abstract class BaseElementDsl extends BaseAttributeDsl permits BaseTemplateDsl {
  BaseElementDsl () {}

  /**
   * Generates the {@code a} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents a(AnchorInstruction... contents) {
    element(StandardElementName.A, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code a} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents a(String text) {
    element(StandardElementName.A, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code abbr} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents abbr(AbbreviationInstruction... contents) {
    element(StandardElementName.ABBR, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code abbr} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents abbr(String text) {
    element(StandardElementName.ABBR, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code article} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents article(ArticleInstruction... contents) {
    element(StandardElementName.ARTICLE, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code article} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents article(String text) {
    element(StandardElementName.ARTICLE, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code b} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents b(BringAttentionToInstruction... contents) {
    element(StandardElementName.B, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code b} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents b(String text) {
    element(StandardElementName.B, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code blockquote} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents blockquote(BlockquoteInstruction... contents) {
    element(StandardElementName.BLOCKQUOTE, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code blockquote} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents blockquote(String text) {
    element(StandardElementName.BLOCKQUOTE, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code body} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents body(BodyInstruction... contents) {
    element(StandardElementName.BODY, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code body} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents body(String text) {
    element(StandardElementName.BODY, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code br} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents br(LineBreakInstruction... contents) {
    element(StandardElementName.BR, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code button} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents button(ButtonInstruction... contents) {
    element(StandardElementName.BUTTON, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code button} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents button(String text) {
    element(StandardElementName.BUTTON, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code clipPath} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents clipPath(ClipPathInstruction... contents) {
    element(StandardElementName.CLIPPATH, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code code} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents code(CodeInstruction... contents) {
    element(StandardElementName.CODE, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code code} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents code(String text) {
    element(StandardElementName.CODE, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code dd} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents dd(DefinitionDescriptionInstruction... contents) {
    element(StandardElementName.DD, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code dd} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents dd(String text) {
    element(StandardElementName.DD, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code defs} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents defs(DefsInstruction... contents) {
    element(StandardElementName.DEFS, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code defs} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents defs(String text) {
    element(StandardElementName.DEFS, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code details} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents details(DetailsInstruction... contents) {
    element(StandardElementName.DETAILS, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code details} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents details(String text) {
    element(StandardElementName.DETAILS, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code div} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents div(DivInstruction... contents) {
    element(StandardElementName.DIV, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code div} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents div(String text) {
    element(StandardElementName.DIV, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code dl} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents dl(DefinitionListInstruction... contents) {
    element(StandardElementName.DL, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code dl} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents dl(String text) {
    element(StandardElementName.DL, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code dt} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents dt(DefinitionTermInstruction... contents) {
    element(StandardElementName.DT, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code dt} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents dt(String text) {
    element(StandardElementName.DT, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code em} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents em(EmphasisInstruction... contents) {
    element(StandardElementName.EM, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code em} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents em(String text) {
    element(StandardElementName.EM, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code fieldset} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents fieldset(FieldsetInstruction... contents) {
    element(StandardElementName.FIELDSET, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code fieldset} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents fieldset(String text) {
    element(StandardElementName.FIELDSET, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code figure} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents figure(FigureInstruction... contents) {
    element(StandardElementName.FIGURE, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code figure} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents figure(String text) {
    element(StandardElementName.FIGURE, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code footer} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents footer(FooterInstruction... contents) {
    element(StandardElementName.FOOTER, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code footer} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents footer(String text) {
    element(StandardElementName.FOOTER, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code form} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents form(FormInstruction... contents) {
    element(StandardElementName.FORM, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code form} attribute or element with the specified text.
   *
   * @param text
   *        the text value of this attribute or element
   *
   * @return an instruction representing this attribute or element.
   */
  protected final ElementContents form(String text) {
    ambiguous(Ambiguous.FORM, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code g} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents g(GInstruction... contents) {
    element(StandardElementName.G, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code g} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents g(String text) {
    element(StandardElementName.G, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code h1} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents h1(Heading1Instruction... contents) {
    element(StandardElementName.H1, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code h1} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents h1(String text) {
    element(StandardElementName.H1, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code h2} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents h2(Heading2Instruction... contents) {
    element(StandardElementName.H2, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code h2} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents h2(String text) {
    element(StandardElementName.H2, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code h3} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents h3(Heading3Instruction... contents) {
    element(StandardElementName.H3, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code h3} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents h3(String text) {
    element(StandardElementName.H3, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code h4} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents h4(Heading4Instruction... contents) {
    element(StandardElementName.H4, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code h4} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents h4(String text) {
    element(StandardElementName.H4, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code h5} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents h5(Heading5Instruction... contents) {
    element(StandardElementName.H5, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code h5} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents h5(String text) {
    element(StandardElementName.H5, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code h6} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents h6(Heading6Instruction... contents) {
    element(StandardElementName.H6, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code h6} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents h6(String text) {
    element(StandardElementName.H6, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code head} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents head(HeadInstruction... contents) {
    element(StandardElementName.HEAD, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code head} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents head(String text) {
    element(StandardElementName.HEAD, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code header} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents header(HeaderInstruction... contents) {
    element(StandardElementName.HEADER, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code header} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents header(String text) {
    element(StandardElementName.HEADER, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code hgroup} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents hgroup(HeadingGroupInstruction... contents) {
    element(StandardElementName.HGROUP, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code hgroup} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents hgroup(String text) {
    element(StandardElementName.HGROUP, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code hr} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents hr(HorizontalRuleInstruction... contents) {
    element(StandardElementName.HR, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code html} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents html(HtmlInstruction... contents) {
    element(StandardElementName.HTML, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code html} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents html(String text) {
    element(StandardElementName.HTML, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code img} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents img(ImageInstruction... contents) {
    element(StandardElementName.IMG, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code input} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents input(InputInstruction... contents) {
    element(StandardElementName.INPUT, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code kbd} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents kbd(KeyboardInputInstruction... contents) {
    element(StandardElementName.KBD, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code kbd} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents kbd(String text) {
    element(StandardElementName.KBD, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code label} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents label(LabelInstruction... contents) {
    element(StandardElementName.LABEL, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code label} attribute or element with the specified text.
   *
   * @param text
   *        the text value of this attribute or element
   *
   * @return an instruction representing this attribute or element.
   */
  protected final ElementContents label(String text) {
    ambiguous(Ambiguous.LABEL, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code legend} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents legend(LegendInstruction... contents) {
    element(StandardElementName.LEGEND, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code legend} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents legend(String text) {
    element(StandardElementName.LEGEND, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code li} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents li(ListItemInstruction... contents) {
    element(StandardElementName.LI, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code li} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents li(String text) {
    element(StandardElementName.LI, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code link} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents link(LinkInstruction... contents) {
    element(StandardElementName.LINK, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code main} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents main(MainInstruction... contents) {
    element(StandardElementName.MAIN, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code main} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents main(String text) {
    element(StandardElementName.MAIN, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code menu} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents menu(MenuInstruction... contents) {
    element(StandardElementName.MENU, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code menu} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents menu(String text) {
    element(StandardElementName.MENU, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code meta} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents meta(MetaInstruction... contents) {
    element(StandardElementName.META, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code nav} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents nav(NavInstruction... contents) {
    element(StandardElementName.NAV, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code nav} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents nav(String text) {
    element(StandardElementName.NAV, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code ol} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents ol(OrderedListInstruction... contents) {
    element(StandardElementName.OL, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code ol} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents ol(String text) {
    element(StandardElementName.OL, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code optgroup} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents optgroup(OptionGroupInstruction... contents) {
    element(StandardElementName.OPTGROUP, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code optgroup} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents optgroup(String text) {
    element(StandardElementName.OPTGROUP, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code option} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents option(OptionInstruction... contents) {
    element(StandardElementName.OPTION, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code option} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents option(String text) {
    element(StandardElementName.OPTION, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code p} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents p(ParagraphInstruction... contents) {
    element(StandardElementName.P, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code p} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents p(String text) {
    element(StandardElementName.P, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code path} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents path(PathInstruction... contents) {
    element(StandardElementName.PATH, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code path} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents path(String text) {
    element(StandardElementName.PATH, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code pre} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents pre(PreInstruction... contents) {
    element(StandardElementName.PRE, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code pre} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents pre(String text) {
    element(StandardElementName.PRE, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code progress} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents progress(ProgressInstruction... contents) {
    element(StandardElementName.PROGRESS, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code progress} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents progress(String text) {
    element(StandardElementName.PROGRESS, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code samp} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents samp(SampleOutputInstruction... contents) {
    element(StandardElementName.SAMP, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code samp} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents samp(String text) {
    element(StandardElementName.SAMP, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code script} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents script(ScriptInstruction... contents) {
    element(StandardElementName.SCRIPT, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code script} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents script(String text) {
    element(StandardElementName.SCRIPT, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code section} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents section(SectionInstruction... contents) {
    element(StandardElementName.SECTION, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code section} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents section(String text) {
    element(StandardElementName.SECTION, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code select} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents select(SelectInstruction... contents) {
    element(StandardElementName.SELECT, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code select} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents select(String text) {
    element(StandardElementName.SELECT, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code small} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents small(SmallInstruction... contents) {
    element(StandardElementName.SMALL, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code small} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents small(String text) {
    element(StandardElementName.SMALL, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code span} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents span(SpanInstruction... contents) {
    element(StandardElementName.SPAN, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code span} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents span(String text) {
    element(StandardElementName.SPAN, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code strong} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents strong(StrongInstruction... contents) {
    element(StandardElementName.STRONG, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code strong} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents strong(String text) {
    element(StandardElementName.STRONG, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code style} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents style(StyleInstruction... contents) {
    element(StandardElementName.STYLE, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code style} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents style(String text) {
    element(StandardElementName.STYLE, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code sub} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents sub(SubscriptInstruction... contents) {
    element(StandardElementName.SUB, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code sub} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents sub(String text) {
    element(StandardElementName.SUB, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code summary} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents summary(SummaryInstruction... contents) {
    element(StandardElementName.SUMMARY, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code summary} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents summary(String text) {
    element(StandardElementName.SUMMARY, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code sup} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents sup(SuperscriptInstruction... contents) {
    element(StandardElementName.SUP, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code sup} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents sup(String text) {
    element(StandardElementName.SUP, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code svg} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents svg(SvgInstruction... contents) {
    element(StandardElementName.SVG, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code svg} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents svg(String text) {
    element(StandardElementName.SVG, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code table} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents table(TableInstruction... contents) {
    element(StandardElementName.TABLE, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code table} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents table(String text) {
    element(StandardElementName.TABLE, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code tbody} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents tbody(TableBodyInstruction... contents) {
    element(StandardElementName.TBODY, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code tbody} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents tbody(String text) {
    element(StandardElementName.TBODY, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code td} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents td(TableDataInstruction... contents) {
    element(StandardElementName.TD, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code td} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents td(String text) {
    element(StandardElementName.TD, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code template} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents template(TemplateInstruction... contents) {
    element(StandardElementName.TEMPLATE, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code template} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents template(String text) {
    element(StandardElementName.TEMPLATE, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code textarea} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents textarea(TextAreaInstruction... contents) {
    element(StandardElementName.TEXTAREA, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code textarea} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents textarea(String text) {
    element(StandardElementName.TEXTAREA, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code th} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents th(TableHeaderInstruction... contents) {
    element(StandardElementName.TH, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code th} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents th(String text) {
    element(StandardElementName.TH, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code thead} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents thead(TableHeadInstruction... contents) {
    element(StandardElementName.THEAD, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code thead} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents thead(String text) {
    element(StandardElementName.THEAD, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code title} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents title(TitleInstruction... contents) {
    element(StandardElementName.TITLE, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code title} attribute or element with the specified text.
   *
   * @param text
   *        the text value of this attribute or element
   *
   * @return an instruction representing this attribute or element.
   */
  protected final ElementContents title(String text) {
    ambiguous(Ambiguous.TITLE, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code tr} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents tr(TableRowInstruction... contents) {
    element(StandardElementName.TR, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code tr} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents tr(String text) {
    element(StandardElementName.TR, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code ul} element with the specified content.
   *
   * @param contents
   *        the attributes and children of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents ul(UnorderedListInstruction... contents) {
    element(StandardElementName.UL, contents);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code ul} element with the specified text.
   *
   * @param text
   *        the text value of this element
   *
   * @return an instruction representing this element.
   */
  protected final ElementContents ul(String text) {
    element(StandardElementName.UL, text);
    return Api.GLOBAL_INSTRUCTION;
  }

  /**
   * Generates the {@code <!DOCTYPE html>} doctype.
   */
  protected final void doctype() {
    api().doctype();
  }

  abstract void ambiguous(Ambiguous name, String text);

  abstract void element(StandardElementName name, String text);

  abstract void element(StandardElementName name, Instruction[] contents);
}
