/*
 * Copyright (C) 2015-2023 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.html;

import objectos.html.internal.HtmlCompiler02;
import objectos.html.internal.HtmlTemplateApi;
import objectos.lang.object.Check;

/**
 * A template in pure Java for generating HTML.
 *
 * <p>
 * This class provides methods for representing HTML code in a Java class. An
 * instance of the class can then be used to generate the represented HTML code.
 *
 * @see objectos.html
 */
public non-sealed abstract class HtmlTemplate extends BaseTemplateDsl {

  HtmlTemplateApi api;

  /**
   * Sole constructor.
   */
  protected HtmlTemplate() {}

  /**
   * Returns a compiled representation of this template.
   *
   * @return compiled representation of this template
   */
  public final Html compile() {
    try {
      api = new HtmlCompiler02();

      api.compilationBegin();

      definition();

      api.compilationEnd();

      api.optimize();

      return api.compile();
    } finally {
      api = null;
    }
  }

  /**
   * Returns the HTML generated by this template.
   *
   * @return the HTML generated by this template
   */
  @Override
  public final String toString() {
    Html compiled;
    compiled = compile();

    return compiled.toString();
  }

  /**
   * Defines the HTML code to be generated by this template.
   */
  protected abstract void definition();

  @Override
  final HtmlTemplateApi api() {
    Check.state(api != null, "api not set");

    return api;
  }

}
