/*
 * Copyright (C) 2016-2023 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.css.util;

@objectos.lang.Generated("objectos.selfgen.CssUtilSpec")
public final class Framework extends objectos.css.CssTemplate {
  @java.lang.Override
  protected final void definition() {
    All();
    Small();
    Medium();
    Large();
    XLarge();
    XLarge2();
  }

  private void All() {
    AllDisplay();
    AllFlexDirection();
    AllJustifyContent();
    AllMinHeight();
  }

  private void Small() {
    SmallDisplay();
    SmallFlexDirection();
    SmallJustifyContent();
    SmallMinHeight();
  }

  private void Medium() {
    MediumDisplay();
    MediumFlexDirection();
    MediumJustifyContent();
    MediumMinHeight();
  }

  private void Large() {
    LargeDisplay();
    LargeFlexDirection();
    LargeJustifyContent();
    LargeMinHeight();
  }

  private void XLarge() {
    XLargeDisplay();
    XLargeFlexDirection();
    XLargeJustifyContent();
    XLargeMinHeight();
  }

  private void XLarge2() {
    XLarge2Display();
    XLarge2FlexDirection();
    XLarge2JustifyContent();
    XLarge2MinHeight();
  }

  private void AllDisplay() {
    style(
      objectos.css.util.All.Display.HIDDEN,
      display(none)
);
    style(
      objectos.css.util.All.Display.BLOCK,
      display(block)
);
    style(
      objectos.css.util.All.Display.FLOW_ROOT,
      display(flowRoot)
);
    style(
      objectos.css.util.All.Display.INLINE_BLOCK,
      display(inlineBlock)
);
    style(
      objectos.css.util.All.Display.INLINE,
      display(inline)
);
    style(
      objectos.css.util.All.Display.FLEX,
      display(flex)
);
    style(
      objectos.css.util.All.Display.INLINE_FLEX,
      display(inlineFlex)
);
    style(
      objectos.css.util.All.Display.GRID,
      display(grid)
);
    style(
      objectos.css.util.All.Display.INLINE_GRID,
      display(inlineGrid)
);
    style(
      objectos.css.util.All.Display.TABLE,
      display(table)
);
    style(
      objectos.css.util.All.Display.TABLE_CAPTION,
      display(tableCaption)
);
    style(
      objectos.css.util.All.Display.TABLE_CELL,
      display(tableCell)
);
    style(
      objectos.css.util.All.Display.TABLE_COLUMN,
      display(tableColumn)
);
    style(
      objectos.css.util.All.Display.TABLE_COLUMN_GROUP,
      display(tableColumnGroup)
);
    style(
      objectos.css.util.All.Display.TABLE_FOOTER_GROUP,
      display(tableFooterGroup)
);
    style(
      objectos.css.util.All.Display.TABLE_HEADER_GROUP,
      display(tableHeaderGroup)
);
    style(
      objectos.css.util.All.Display.TABLE_ROW_GROUP,
      display(tableRowGroup)
);
    style(
      objectos.css.util.All.Display.TABLE_ROW,
      display(tableRow)
);
  }

  private void AllFlexDirection() {
    style(
      objectos.css.util.All.FlexDirection.ROW,
      flexDirection(row)
);
    style(
      objectos.css.util.All.FlexDirection.ROW_REVERSE,
      flexDirection(rowReverse)
);
    style(
      objectos.css.util.All.FlexDirection.COLUMN,
      flexDirection(column)
);
    style(
      objectos.css.util.All.FlexDirection.COLUMN_REVERSE,
      flexDirection(columnReverse)
);
  }

  private void AllJustifyContent() {
    style(
      objectos.css.util.All.JustifyContent.START,
      justifyContent(flexStart)
);
    style(
      objectos.css.util.All.JustifyContent.CENTER,
      justifyContent(center)
);
    style(
      objectos.css.util.All.JustifyContent.END,
      justifyContent(flexEnd)
);
    style(
      objectos.css.util.All.JustifyContent.BETWEEN,
      justifyContent(spaceBetween)
);
    style(
      objectos.css.util.All.JustifyContent.AROUND,
      justifyContent(spaceAround)
);
  }

  private void AllMinHeight() {
    style(
      objectos.css.util.All.MinHeight.V0,
      minHeight($0)
);
    style(
      objectos.css.util.All.MinHeight.FULL,
      minHeight(pct(100))
);
    style(
      objectos.css.util.All.MinHeight.SCREEN,
      minHeight(vh(100))
);
  }

  private void SmallDisplay() {
    media(
      minWidth(px(640)),
      style(
        objectos.css.util.Small.Display.HIDDEN,
        display(none)
),
      style(
        objectos.css.util.Small.Display.BLOCK,
        display(block)
),
      style(
        objectos.css.util.Small.Display.FLOW_ROOT,
        display(flowRoot)
),
      style(
        objectos.css.util.Small.Display.INLINE_BLOCK,
        display(inlineBlock)
),
      style(
        objectos.css.util.Small.Display.INLINE,
        display(inline)
),
      style(
        objectos.css.util.Small.Display.FLEX,
        display(flex)
),
      style(
        objectos.css.util.Small.Display.INLINE_FLEX,
        display(inlineFlex)
),
      style(
        objectos.css.util.Small.Display.GRID,
        display(grid)
),
      style(
        objectos.css.util.Small.Display.INLINE_GRID,
        display(inlineGrid)
),
      style(
        objectos.css.util.Small.Display.TABLE,
        display(table)
),
      style(
        objectos.css.util.Small.Display.TABLE_CAPTION,
        display(tableCaption)
),
      style(
        objectos.css.util.Small.Display.TABLE_CELL,
        display(tableCell)
),
      style(
        objectos.css.util.Small.Display.TABLE_COLUMN,
        display(tableColumn)
),
      style(
        objectos.css.util.Small.Display.TABLE_COLUMN_GROUP,
        display(tableColumnGroup)
),
      style(
        objectos.css.util.Small.Display.TABLE_FOOTER_GROUP,
        display(tableFooterGroup)
),
      style(
        objectos.css.util.Small.Display.TABLE_HEADER_GROUP,
        display(tableHeaderGroup)
),
      style(
        objectos.css.util.Small.Display.TABLE_ROW_GROUP,
        display(tableRowGroup)
),
      style(
        objectos.css.util.Small.Display.TABLE_ROW,
        display(tableRow)
));
  }

  private void SmallFlexDirection() {
    media(
      minWidth(px(640)),
      style(
        objectos.css.util.Small.FlexDirection.ROW,
        flexDirection(row)
),
      style(
        objectos.css.util.Small.FlexDirection.ROW_REVERSE,
        flexDirection(rowReverse)
),
      style(
        objectos.css.util.Small.FlexDirection.COLUMN,
        flexDirection(column)
),
      style(
        objectos.css.util.Small.FlexDirection.COLUMN_REVERSE,
        flexDirection(columnReverse)
));
  }

  private void SmallJustifyContent() {
    media(
      minWidth(px(640)),
      style(
        objectos.css.util.Small.JustifyContent.START,
        justifyContent(flexStart)
),
      style(
        objectos.css.util.Small.JustifyContent.CENTER,
        justifyContent(center)
),
      style(
        objectos.css.util.Small.JustifyContent.END,
        justifyContent(flexEnd)
),
      style(
        objectos.css.util.Small.JustifyContent.BETWEEN,
        justifyContent(spaceBetween)
),
      style(
        objectos.css.util.Small.JustifyContent.AROUND,
        justifyContent(spaceAround)
));
  }

  private void SmallMinHeight() {
    media(
      minWidth(px(640)),
      style(
        objectos.css.util.Small.MinHeight.V0,
        minHeight($0)
),
      style(
        objectos.css.util.Small.MinHeight.FULL,
        minHeight(pct(100))
),
      style(
        objectos.css.util.Small.MinHeight.SCREEN,
        minHeight(vh(100))
));
  }

  private void MediumDisplay() {
    media(
      minWidth(px(768)),
      style(
        objectos.css.util.Medium.Display.HIDDEN,
        display(none)
),
      style(
        objectos.css.util.Medium.Display.BLOCK,
        display(block)
),
      style(
        objectos.css.util.Medium.Display.FLOW_ROOT,
        display(flowRoot)
),
      style(
        objectos.css.util.Medium.Display.INLINE_BLOCK,
        display(inlineBlock)
),
      style(
        objectos.css.util.Medium.Display.INLINE,
        display(inline)
),
      style(
        objectos.css.util.Medium.Display.FLEX,
        display(flex)
),
      style(
        objectos.css.util.Medium.Display.INLINE_FLEX,
        display(inlineFlex)
),
      style(
        objectos.css.util.Medium.Display.GRID,
        display(grid)
),
      style(
        objectos.css.util.Medium.Display.INLINE_GRID,
        display(inlineGrid)
),
      style(
        objectos.css.util.Medium.Display.TABLE,
        display(table)
),
      style(
        objectos.css.util.Medium.Display.TABLE_CAPTION,
        display(tableCaption)
),
      style(
        objectos.css.util.Medium.Display.TABLE_CELL,
        display(tableCell)
),
      style(
        objectos.css.util.Medium.Display.TABLE_COLUMN,
        display(tableColumn)
),
      style(
        objectos.css.util.Medium.Display.TABLE_COLUMN_GROUP,
        display(tableColumnGroup)
),
      style(
        objectos.css.util.Medium.Display.TABLE_FOOTER_GROUP,
        display(tableFooterGroup)
),
      style(
        objectos.css.util.Medium.Display.TABLE_HEADER_GROUP,
        display(tableHeaderGroup)
),
      style(
        objectos.css.util.Medium.Display.TABLE_ROW_GROUP,
        display(tableRowGroup)
),
      style(
        objectos.css.util.Medium.Display.TABLE_ROW,
        display(tableRow)
));
  }

  private void MediumFlexDirection() {
    media(
      minWidth(px(768)),
      style(
        objectos.css.util.Medium.FlexDirection.ROW,
        flexDirection(row)
),
      style(
        objectos.css.util.Medium.FlexDirection.ROW_REVERSE,
        flexDirection(rowReverse)
),
      style(
        objectos.css.util.Medium.FlexDirection.COLUMN,
        flexDirection(column)
),
      style(
        objectos.css.util.Medium.FlexDirection.COLUMN_REVERSE,
        flexDirection(columnReverse)
));
  }

  private void MediumJustifyContent() {
    media(
      minWidth(px(768)),
      style(
        objectos.css.util.Medium.JustifyContent.START,
        justifyContent(flexStart)
),
      style(
        objectos.css.util.Medium.JustifyContent.CENTER,
        justifyContent(center)
),
      style(
        objectos.css.util.Medium.JustifyContent.END,
        justifyContent(flexEnd)
),
      style(
        objectos.css.util.Medium.JustifyContent.BETWEEN,
        justifyContent(spaceBetween)
),
      style(
        objectos.css.util.Medium.JustifyContent.AROUND,
        justifyContent(spaceAround)
));
  }

  private void MediumMinHeight() {
    media(
      minWidth(px(768)),
      style(
        objectos.css.util.Medium.MinHeight.V0,
        minHeight($0)
),
      style(
        objectos.css.util.Medium.MinHeight.FULL,
        minHeight(pct(100))
),
      style(
        objectos.css.util.Medium.MinHeight.SCREEN,
        minHeight(vh(100))
));
  }

  private void LargeDisplay() {
    media(
      minWidth(px(1024)),
      style(
        objectos.css.util.Large.Display.HIDDEN,
        display(none)
),
      style(
        objectos.css.util.Large.Display.BLOCK,
        display(block)
),
      style(
        objectos.css.util.Large.Display.FLOW_ROOT,
        display(flowRoot)
),
      style(
        objectos.css.util.Large.Display.INLINE_BLOCK,
        display(inlineBlock)
),
      style(
        objectos.css.util.Large.Display.INLINE,
        display(inline)
),
      style(
        objectos.css.util.Large.Display.FLEX,
        display(flex)
),
      style(
        objectos.css.util.Large.Display.INLINE_FLEX,
        display(inlineFlex)
),
      style(
        objectos.css.util.Large.Display.GRID,
        display(grid)
),
      style(
        objectos.css.util.Large.Display.INLINE_GRID,
        display(inlineGrid)
),
      style(
        objectos.css.util.Large.Display.TABLE,
        display(table)
),
      style(
        objectos.css.util.Large.Display.TABLE_CAPTION,
        display(tableCaption)
),
      style(
        objectos.css.util.Large.Display.TABLE_CELL,
        display(tableCell)
),
      style(
        objectos.css.util.Large.Display.TABLE_COLUMN,
        display(tableColumn)
),
      style(
        objectos.css.util.Large.Display.TABLE_COLUMN_GROUP,
        display(tableColumnGroup)
),
      style(
        objectos.css.util.Large.Display.TABLE_FOOTER_GROUP,
        display(tableFooterGroup)
),
      style(
        objectos.css.util.Large.Display.TABLE_HEADER_GROUP,
        display(tableHeaderGroup)
),
      style(
        objectos.css.util.Large.Display.TABLE_ROW_GROUP,
        display(tableRowGroup)
),
      style(
        objectos.css.util.Large.Display.TABLE_ROW,
        display(tableRow)
));
  }

  private void LargeFlexDirection() {
    media(
      minWidth(px(1024)),
      style(
        objectos.css.util.Large.FlexDirection.ROW,
        flexDirection(row)
),
      style(
        objectos.css.util.Large.FlexDirection.ROW_REVERSE,
        flexDirection(rowReverse)
),
      style(
        objectos.css.util.Large.FlexDirection.COLUMN,
        flexDirection(column)
),
      style(
        objectos.css.util.Large.FlexDirection.COLUMN_REVERSE,
        flexDirection(columnReverse)
));
  }

  private void LargeJustifyContent() {
    media(
      minWidth(px(1024)),
      style(
        objectos.css.util.Large.JustifyContent.START,
        justifyContent(flexStart)
),
      style(
        objectos.css.util.Large.JustifyContent.CENTER,
        justifyContent(center)
),
      style(
        objectos.css.util.Large.JustifyContent.END,
        justifyContent(flexEnd)
),
      style(
        objectos.css.util.Large.JustifyContent.BETWEEN,
        justifyContent(spaceBetween)
),
      style(
        objectos.css.util.Large.JustifyContent.AROUND,
        justifyContent(spaceAround)
));
  }

  private void LargeMinHeight() {
    media(
      minWidth(px(1024)),
      style(
        objectos.css.util.Large.MinHeight.V0,
        minHeight($0)
),
      style(
        objectos.css.util.Large.MinHeight.FULL,
        minHeight(pct(100))
),
      style(
        objectos.css.util.Large.MinHeight.SCREEN,
        minHeight(vh(100))
));
  }

  private void XLargeDisplay() {
    media(
      minWidth(px(1280)),
      style(
        objectos.css.util.XLarge.Display.HIDDEN,
        display(none)
),
      style(
        objectos.css.util.XLarge.Display.BLOCK,
        display(block)
),
      style(
        objectos.css.util.XLarge.Display.FLOW_ROOT,
        display(flowRoot)
),
      style(
        objectos.css.util.XLarge.Display.INLINE_BLOCK,
        display(inlineBlock)
),
      style(
        objectos.css.util.XLarge.Display.INLINE,
        display(inline)
),
      style(
        objectos.css.util.XLarge.Display.FLEX,
        display(flex)
),
      style(
        objectos.css.util.XLarge.Display.INLINE_FLEX,
        display(inlineFlex)
),
      style(
        objectos.css.util.XLarge.Display.GRID,
        display(grid)
),
      style(
        objectos.css.util.XLarge.Display.INLINE_GRID,
        display(inlineGrid)
),
      style(
        objectos.css.util.XLarge.Display.TABLE,
        display(table)
),
      style(
        objectos.css.util.XLarge.Display.TABLE_CAPTION,
        display(tableCaption)
),
      style(
        objectos.css.util.XLarge.Display.TABLE_CELL,
        display(tableCell)
),
      style(
        objectos.css.util.XLarge.Display.TABLE_COLUMN,
        display(tableColumn)
),
      style(
        objectos.css.util.XLarge.Display.TABLE_COLUMN_GROUP,
        display(tableColumnGroup)
),
      style(
        objectos.css.util.XLarge.Display.TABLE_FOOTER_GROUP,
        display(tableFooterGroup)
),
      style(
        objectos.css.util.XLarge.Display.TABLE_HEADER_GROUP,
        display(tableHeaderGroup)
),
      style(
        objectos.css.util.XLarge.Display.TABLE_ROW_GROUP,
        display(tableRowGroup)
),
      style(
        objectos.css.util.XLarge.Display.TABLE_ROW,
        display(tableRow)
));
  }

  private void XLargeFlexDirection() {
    media(
      minWidth(px(1280)),
      style(
        objectos.css.util.XLarge.FlexDirection.ROW,
        flexDirection(row)
),
      style(
        objectos.css.util.XLarge.FlexDirection.ROW_REVERSE,
        flexDirection(rowReverse)
),
      style(
        objectos.css.util.XLarge.FlexDirection.COLUMN,
        flexDirection(column)
),
      style(
        objectos.css.util.XLarge.FlexDirection.COLUMN_REVERSE,
        flexDirection(columnReverse)
));
  }

  private void XLargeJustifyContent() {
    media(
      minWidth(px(1280)),
      style(
        objectos.css.util.XLarge.JustifyContent.START,
        justifyContent(flexStart)
),
      style(
        objectos.css.util.XLarge.JustifyContent.CENTER,
        justifyContent(center)
),
      style(
        objectos.css.util.XLarge.JustifyContent.END,
        justifyContent(flexEnd)
),
      style(
        objectos.css.util.XLarge.JustifyContent.BETWEEN,
        justifyContent(spaceBetween)
),
      style(
        objectos.css.util.XLarge.JustifyContent.AROUND,
        justifyContent(spaceAround)
));
  }

  private void XLargeMinHeight() {
    media(
      minWidth(px(1280)),
      style(
        objectos.css.util.XLarge.MinHeight.V0,
        minHeight($0)
),
      style(
        objectos.css.util.XLarge.MinHeight.FULL,
        minHeight(pct(100))
),
      style(
        objectos.css.util.XLarge.MinHeight.SCREEN,
        minHeight(vh(100))
));
  }

  private void XLarge2Display() {
    media(
      minWidth(px(1536)),
      style(
        objectos.css.util.XLarge2.Display.HIDDEN,
        display(none)
),
      style(
        objectos.css.util.XLarge2.Display.BLOCK,
        display(block)
),
      style(
        objectos.css.util.XLarge2.Display.FLOW_ROOT,
        display(flowRoot)
),
      style(
        objectos.css.util.XLarge2.Display.INLINE_BLOCK,
        display(inlineBlock)
),
      style(
        objectos.css.util.XLarge2.Display.INLINE,
        display(inline)
),
      style(
        objectos.css.util.XLarge2.Display.FLEX,
        display(flex)
),
      style(
        objectos.css.util.XLarge2.Display.INLINE_FLEX,
        display(inlineFlex)
),
      style(
        objectos.css.util.XLarge2.Display.GRID,
        display(grid)
),
      style(
        objectos.css.util.XLarge2.Display.INLINE_GRID,
        display(inlineGrid)
),
      style(
        objectos.css.util.XLarge2.Display.TABLE,
        display(table)
),
      style(
        objectos.css.util.XLarge2.Display.TABLE_CAPTION,
        display(tableCaption)
),
      style(
        objectos.css.util.XLarge2.Display.TABLE_CELL,
        display(tableCell)
),
      style(
        objectos.css.util.XLarge2.Display.TABLE_COLUMN,
        display(tableColumn)
),
      style(
        objectos.css.util.XLarge2.Display.TABLE_COLUMN_GROUP,
        display(tableColumnGroup)
),
      style(
        objectos.css.util.XLarge2.Display.TABLE_FOOTER_GROUP,
        display(tableFooterGroup)
),
      style(
        objectos.css.util.XLarge2.Display.TABLE_HEADER_GROUP,
        display(tableHeaderGroup)
),
      style(
        objectos.css.util.XLarge2.Display.TABLE_ROW_GROUP,
        display(tableRowGroup)
),
      style(
        objectos.css.util.XLarge2.Display.TABLE_ROW,
        display(tableRow)
));
  }

  private void XLarge2FlexDirection() {
    media(
      minWidth(px(1536)),
      style(
        objectos.css.util.XLarge2.FlexDirection.ROW,
        flexDirection(row)
),
      style(
        objectos.css.util.XLarge2.FlexDirection.ROW_REVERSE,
        flexDirection(rowReverse)
),
      style(
        objectos.css.util.XLarge2.FlexDirection.COLUMN,
        flexDirection(column)
),
      style(
        objectos.css.util.XLarge2.FlexDirection.COLUMN_REVERSE,
        flexDirection(columnReverse)
));
  }

  private void XLarge2JustifyContent() {
    media(
      minWidth(px(1536)),
      style(
        objectos.css.util.XLarge2.JustifyContent.START,
        justifyContent(flexStart)
),
      style(
        objectos.css.util.XLarge2.JustifyContent.CENTER,
        justifyContent(center)
),
      style(
        objectos.css.util.XLarge2.JustifyContent.END,
        justifyContent(flexEnd)
),
      style(
        objectos.css.util.XLarge2.JustifyContent.BETWEEN,
        justifyContent(spaceBetween)
),
      style(
        objectos.css.util.XLarge2.JustifyContent.AROUND,
        justifyContent(spaceAround)
));
  }

  private void XLarge2MinHeight() {
    media(
      minWidth(px(1536)),
      style(
        objectos.css.util.XLarge2.MinHeight.V0,
        minHeight($0)
),
      style(
        objectos.css.util.XLarge2.MinHeight.FULL,
        minHeight(pct(100))
),
      style(
        objectos.css.util.XLarge2.MinHeight.SCREEN,
        minHeight(vh(100))
));
  }
}
