/*
 * Copyright (C) 2015-2023 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.selfgen.css;

import static objectos.selfgen.css.Util.generate;
import static org.testng.Assert.assertEquals;

import java.io.IOException;
import org.testng.annotations.Test;

public class CssSelfGen00Test {

  @Test
  public void propertyBorderWidth() throws IOException {
    var spec = new CssSelfGen() {
      @Override
      protected void definition() {
        var length = length("em", "px");

        var lineWidth = t(
          "LineWidth",

          length,
          k("thin"),
          k("medium"),
          k("thick")
        );

        property(
          "border-width",

          sig(lineWidth, "all"),
          sig(lineWidth, "vertical", lineWidth, "horizontal"),
          sig(lineWidth, "top", lineWidth, "vertical", lineWidth, "bottom"),
          sig(lineWidth, "top", lineWidth, "right", lineWidth, "bottom", lineWidth, "left")
        );
      }
    };

    var result = generate(spec);

    assertEquals(
      result.get("objectox/css/Property.java"),

      """
      /*
       * Copyright (C) 2016-2023 Objectos Software LTDA.
       *
       * Licensed under the Apache License, Version 2.0 (the "License");
       * you may not use this file except in compliance with the License.
       * You may obtain a copy of the License at
       *
       * http://www.apache.org/licenses/LICENSE-2.0
       *
       * Unless required by applicable law or agreed to in writing, software
       * distributed under the License is distributed on an "AS IS" BASIS,
       * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       * See the License for the specific language governing permissions and
       * limitations under the License.
       */
      package objectox.css;

      // Generated by selfgen.css.CssSpec. Do not edit!
      public enum Property {
        BORDER_WIDTH("border-width");

        private static final Property[] VALUES = values();

        public final String cssName;

        private Property(String cssName) {
          this.cssName = cssName;
        }

        public static Property byOrdinal(int ordinal) {
          return VALUES[ordinal];
        }

        @Override
        public final String toString() {
          return cssName;
        }
      }
      """
    );
  }

}