name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Cache local repository
      uses: actions/cache@v4
      with:
        path: ~/.cache/objectos
        key: ${{ runner.os }}-objectos-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-objectos-

    - name: Build it
      run: make

    - name: Archive test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: work/test-output